---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: protect-api-infrastructure-apimanagement-weather
  namespace: apps
  labels:
    subscription: standard
spec:
  openApiSpec:
    path: /openapi.yaml
