---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: protect-api-infrastructure-apimanagement-whoami
  namespace: apps
spec:
  groups:
    - external
  apis:
   - name: protect-api-infrastructure-apimanagement-whoami
