# Default values for neo-helm-chart.
image:
  name: gcr.io/traefiklabs/neo-agent
  pullSecrets:
    - name: gcr-access-token
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# User token to access to neo
token: "${TOKEN_CLUSTER}"

deployment:
  args:
    - --log-level=debug
    - --platform-url=http://platform.docker.localhost/agent
