---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-nginx
  namespace: whoami
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    neo.traefik.io/access-control-policy: "my-acp@whoami"
spec:
  ingressClassName: nginx-k8s
  tls:
    - hosts:
        - whoami.nginx.neo.demo.traefiklabs.tech
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: nginx-tls
  rules:
    - host: whoami.nginx.neo.demo.traefiklabs.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
          - path: /httpbin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
