---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-traefik
  namespace: whoami
#   annotations:
#     neo.traefik.io/access-control-policy: "my-acp@app"
spec:
  ingressClassName: traefik-lb
  rules:
    - host: whoami.traefik.neo.demo.traefiklabs.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: whoami
data:
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JR2tBZ0VCQkRCL1BoWXFHMDhmU0E4UEEvKy8vYzFVbTEydGJZYnkvN1BXTDhrN0JvWm5BZ3RObWFnc3UwckgKZk1adVZGYmxHOHFnQndZRks0RUVBQ0toWkFOaUFBVEtRUDdBVXhNN0FoL2hoUVM1NkVrT1VKdS9xOXNVdW1TcApidk1NSzgxOU1SZmJtOUREeDM3b3JqMU5TYlBJc1ZQejJNKy9IK0tCZE9PdUE5T1B3SitoeHltQjZUNDNJRnlrCk5EeFA2WG5FNm5PZlNwYzFBM3FQUXFuc3BkSHlrWVk9Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVuakNDQTRhZ0F3SUJBZ0lTQTNNb0N2MjZZZ1VjVnRRc1U2VHlBNEg0TUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlNVEExTURZeE16QTRNamhhRncweU1UQTRNRFF4TXpBNE1qaGFNQzR4TERBcUJnTlZCQU1NCkl5b3VkSEpoWldacGF5NXVaVzh1WkdWdGJ5NTBjbUZsWm1scmJHRmljeTUwWldOb01IWXdFQVlIS29aSXpqMEMKQVFZRks0RUVBQ0lEWWdBRXlrRCt3Rk1UT3dJZjRZVUV1ZWhKRGxDYnY2dmJGTHBrcVc3ekRDdk5mVEVYMjV2UQp3OGQrNks0OVRVbXp5TEZUODlqUHZ4L2lnWFRqcmdQVGo4Q2ZvY2NwZ2VrK055QmNwRFE4VCtsNXhPcHpuMHFYCk5RTjZqMEtwN0tYUjhwR0dvNElDWGpDQ0Fsb3dEZ1lEVlIwUEFRSC9CQVFEQWdlQU1CMEdBMVVkSlFRV01CUUcKQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNEWkVhSApoclNyd1Q2Tld0cVZMeTlCWTFjaGJ6QWZCZ05WSFNNRUdEQVdnQlFVTHJNWHQxaFd5NjVRQ1VEbUg2K2RpeFRDCnhqQlZCZ2dyQmdFRkJRY0JBUVJKTUVjd0lRWUlLd1lCQlFVSE1BR0dGV2gwZEhBNkx5OXlNeTV2TG14bGJtTnkKTG05eVp6QWlCZ2dyQmdFRkJRY3dBb1lXYUhSMGNEb3ZMM0l6TG1rdWJHVnVZM0l1YjNKbkx6QXVCZ05WSFJFRQpKekFsZ2lNcUxuUnlZV1ZtYVdzdWJtVnZMbVJsYlc4dWRISmhaV1pwYTJ4aFluTXVkR1ZqYURCTUJnTlZIU0FFClJUQkRNQWdHQm1lQkRBRUNBVEEzQmdzckJnRUVBWUxmRXdFQkFUQW9NQ1lHQ0NzR0FRVUZCd0lCRmhwb2RIUncKT2k4dlkzQnpMbXhsZEhObGJtTnllWEIwTG05eVp6Q0NBUVFHQ2lzR0FRUUIxbmtDQkFJRWdmVUVnZklBOEFCMgpBRnpjUTVMKzVxdEZSTEZlbXRSVzVoQTMrOVg2Ujl5aGM1U3lYdWIyeHc3S0FBQUJlVUlDS21RQUFBUURBRWN3ClJRSWhBS2I2ZnhkSHlubnFyL1pBVlA5TzZsZWZiMXFXWm9Yak52UEZ1M0YzSG5mQ0FpQk0xVFRzeit3dlp1TUcKU25pSkFVdGdiNkcrRUhsOGdDT3dZbGhMLzZGaHJ3QjJBUFpjbEMvUmR6QWlGRlFZQ0RDVVZvN2pUUk1aTTcvZgpEQzhnQzh4TzhXVGpBQUFCZVVJQ0tmY0FBQVFEQUVjd1JRSWhBT0hDdUJkcmtQL0hqa0h6dm1ISGFKM1NtQ0w2CmdIQkovWFhlZHZQRTVNSVRBaUI1T09kblo5WGR5aG9WU2dORmJ3eFZjVyt1MDJZMlJXYVVHT0pJUlNHZ29EQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaVQrZEE3V1o5QVVmVU93cEJ1YmdnZnhUSzBLQm9YOEgxanNwQndmWgpBOXNEMmd1ZVZaK0NMem5WTUEvQisvSnAwSGdWenBQck95K1lOV1ZZZExvY0RRblRvVXJ4ek4yUm01RWRPSU05ClhkbUlVbVZEcVIyaU5yRzViZ3VIZEorcEZVVDcycDBNaXNIejlMSzZrQnF0VnZKYkdzdFFpUzhiakhObVZaQksKWW5rS1FTbzR3VXQrRkRYdGE3a0JFRlhaUkJiZ3pTdG81ZUFLSGFkbmxFS3R3NERVT3IxTEZIdVo0MXhLWHBJQQorTG4vd2RvTVM3bUJXWDRRYkM5dTdBSWtiOVdKSGp0UG85NGJnOXpCMWF3aHZUSGxKWHp0TmJRc0crNjlFa0IyCkJKSjc2UjZVajhFNWpBNDE0bEQzOHp5bDlqTHJaRUM5ZmlaSWpvb2kvMDVtSnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRVpUQ0NBMDJnQXdJQkFnSVFRQUYxQklNVXBNZ2hqSVNwREJiTjN6QU5CZ2txaGtpRzl3MEJBUXNGQURBLwpNU1F3SWdZRFZRUUtFeHRFYVdkcGRHRnNJRk5wWjI1aGRIVnlaU0JVY25WemRDQkRieTR4RnpBVkJnTlZCQU1UCkRrUlRWQ0JTYjI5MElFTkJJRmd6TUI0WERUSXdNVEF3TnpFNU1qRTBNRm9YRFRJeE1Ea3lPVEU1TWpFME1Gb3cKTWpFTE1Ba0dBMVVFQmhNQ1ZWTXhGakFVQmdOVkJBb1REVXhsZENkeklFVnVZM0o1Y0hReEN6QUpCZ05WQkFNVApBbEl6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1d0lWS016Mm9KVFREeExzCmpWV1N3L2lDOFptbWVrS0lwMTBtcXJVcnVjVk1zYStPYS9sMXlLUFhEMGVVRkZVMVY0eWVxS0k1R2ZXQ1BFS3AKVG03MU84TXUyNDNBc0Z6eldUam43YzlwOEZvTEc3N0FsQ1FsaC9vM2NiTVQ1eHlzNFp2djIrUTdSVkpGbHFuQgpVODQweUZMdXRhN3RqOTVnY09LbFZLdTJiUTZYcFVBMGF5dlR2R2JyWmpSOCttdUxqMWNwbWZnd0YxMjZjbS83CmdjV3Qwb1pZUFJmSDV3bTc4U3YzaHR6QjJuRmQxRWJqekswbHdZaThZR2QxWnJQeEdQZWlYT1pUL3pxSXRrZWwKL3hNWTZwZ0pkeitkVS9uUEFlWDFwbkFYRks5anBQK1pzNU9kM0ZPbkJ2NUloUjJoYWE0bGRic1R6RklEOWUxUgpvWXZiRlFJREFRQUJvNElCYURDQ0FXUXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFPQmdOVkhROEJBZjhFCkJBTUNBWVl3U3dZSUt3WUJCUVVIQVFFRVB6QTlNRHNHQ0NzR0FRVUZCekFDaGk5b2RIUndPaTh2WVhCd2N5NXAKWkdWdWRISjFjM1F1WTI5dEwzSnZiM1J6TDJSemRISnZiM1JqWVhnekxuQTNZekFmQmdOVkhTTUVHREFXZ0JURQpwN0drZXl4eCt0dmhTNUIxLzhRVllJV0pFREJVQmdOVkhTQUVUVEJMTUFnR0JtZUJEQUVDQVRBL0Jnc3JCZ0VFCkFZTGZFd0VCQVRBd01DNEdDQ3NHQVFVRkJ3SUJGaUpvZEhSd09pOHZZM0J6TG5KdmIzUXRlREV1YkdWMGMyVnUKWTNKNWNIUXViM0puTUR3R0ExVWRId1ExTURNd01hQXZvQzJHSzJoMGRIQTZMeTlqY213dWFXUmxiblJ5ZFhOMApMbU52YlM5RVUxUlNUMDlVUTBGWU0wTlNUQzVqY213d0hRWURWUjBPQkJZRUZCUXVzeGUzV0ZiTHJsQUpRT1lmCnI1MkxGTUxHTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBUUVBMlV6Z3lmV0VpRGN4MjdzVDRyUDhpMnRpRW14WXQwbCtQQUszcUI4b1lldk80QzV6NzBrSAplaldFSHgydGFQRFkvbGFCTDIxL1dLWnVOVFlRSEhQRDViMXRYZ0hYYm5MN0txQzQwMWRrNVZ2Q2FkVFFzdmQ4ClM4TVhqb2h5Yzl6OS9HMjk0OGtMam1FNkZsaDlkRFlyVllBOXgyTytoRVBHT2FFT2ExZWVQeW5CZ1BheXZVZkwKcWpCc3R6TGhXVlFMR0FrWFhtTnMrNVpuUEJ4ekRKT0x4aEYySkliZVFBY0g1SDB0WnJVbG81Wll5T3FBN3M5cApPNWI4NW8zQU0vT0orQ2t0RkJRdGZ2QmhjSlZkOXd2bHdQc2srdXlPeTJISTdtTnhLS2dzQlR0Mzc1dGVBMlR3ClVkSGtoVk5jc0FLWDFIN0dOTkxPRUFEa3NkODZ3dW9Ydmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app-tls
  namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`app.traefik.neo.demo.traefiklabs.tech`)
      services:
        - name: whoami
          port: 80
    - kind: Rule
      match: Path(`/app`)
      services:
        - name: whoami
          port: 80
  tls:
    secretName: tls
