---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: neo-agent
  namespace: neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo-agent
  template:
    metadata:
      labels:
        app: neo-agent
    spec:
      serviceAccountName: neo-agent
      containers:
        - name: neo-agent
          image: gcr.io/traefiklabs/neo-agent:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/run/neo-agent/
              name: certs
          args:
            - --log-level=debug
            - --log-format=console
      volumes:
        - name: certs
          secret:
            secretName: neo-certs
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem

---
apiVersion: v1
kind: Service
metadata:
  name: neo-agent
  namespace: neo
  labels:
    app: neo-agent
spec:
  type: ClusterIP
  ports:
    - port: 443
      name: neo-agent-webhook
    - port: 80
      name: neo-agent-auth
    - port: 40000
      name: neo-agent-debug
  selector:
    app: neo-agent

---
apiVersion: v1
kind: Secret
metadata:
  name: neo-certs
  namespace: neo
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdLZ0F3SUJBZ0lRSVZWKzVYQ0pPV295Z0tpNmxHandTVEFLQmdncWhrak9QUVFEQWpBU01SQXcKRGdZRFZRUUtFd2RCWTIxbElFTnZNQ0FYRFRJeE1ETXdNekE1TlRrME1sb1lEekl4TWpFd01qQTNNRGsxT1RReQpXakFTTVJBd0RnWURWUVFLRXdkQlkyMWxJRU52TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFCjFxeWc5cFpUcXJGUWd4Y3BoYmw5anJXYXdkbGJmeU9YSFZ2MlZQemNueDhhQmpFK3h4Z2srRWd1eDcwV2NXaVQKNWhVdDBGOTlIUGg0SnRMdk9KdXd1Nk9CbHpDQmxEQU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0V3WURWUjBsQkF3dwpDZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVS1FxT1hIbEhXTWZjCi92M3ppOFFZYnd4SGVKMHdQUVlEVlIwUkJEWXdOSUlmYm1WdkxXRm5aVzUwTG01bGJ5NXpkbU11WTJ4MWMzUmwKY2k1c2IyTmhiSUlSYm1WdkxXRm5aVzUwTG01bGJ5NXpkbU13Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnR2hmYwphNEdmZEM3L1hiYzgyRTF5YVVPY0tVYi91bnRPOVU0Uy8yc0lWREVDSUVpaTE2TC9UeHoyUlM1WmowQ0p1RGwxCnB2clZmVGUzZHRtRm1YVDE4ODExCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3BGVHJldFE3Z1R2TlRWU3MKT3NQck9MUUppdERDN2lsQ0R2NG1NcWR3Q1BXaFJBTkNBQVRXcktEMmxsT3FzVkNERnltRnVYMk90WnJCMlZ0LwpJNWNkVy9aVS9OeWZIeG9HTVQ3SEdDVDRTQzdIdlJaeGFKUG1GUzNRWDMwYytIZ20wdTg0bTdDNwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
