---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: access-control-apimanagement-complex-weather
  namespace: apps
  labels:
    subscription: standard
spec:
  openApiSpec:
    path: /openapi.yaml
    operationSets:
      - name: get-forecast
        matchers:
          - pathPrefix: "/weather"
            methods: [ "GET" ]
      - name: patch-forecast
        matchers:
          - pathPrefix: "/weather/0"
            methods: [ "PATCH" ]

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: access-control-apimanagement-complex-weather-external
  namespace: apps
spec:
  groups:
    - external
  apiSelector:
    matchLabels:
      subscription: standard
  operationFilter:
    include:
      - get-forecast

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: access-control-apimanagement-complex-weather-admin
  namespace: apps
spec:
  groups:
    - admin
  apiSelector:
    matchLabels:
      subscription: standard
  operationFilter:
    include:
      - get-forecast
      - patch-forecast

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: access-control-apimanagement-complex-weather
  namespace: apps
  annotations:
    hub.traefik.io/api: access-control-apimanagement-complex-weather
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`api.access-control.apimanagement.docker.localhost`) && PathRegexp(`^/complex/weather(/([0-9]+|openapi.yaml))?$`)
    kind: Rule
    services:
    - name: weather-app
      port: 3000
    middlewares:
      - name: stripprefix-weather
