---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: access-control-apimanagement-simple-admin
  namespace: admin
spec: {}

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: access-control-apimanagement-simple-admin
  namespace: admin
spec:
  groups: # <=== Allow access only for this group
    - admin
  apis: # <=== Select only this API
    - name: access-control-apimanagement-simple-admin

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: access-control-apimanagement-simple-admin
  namespace: admin
  annotations:
    hub.traefik.io/api: access-control-apimanagement-simple-admin
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`api.access-control.apimanagement.docker.localhost`) && Path(`/simple/admin`)
    kind: Rule
    services:
    - name: admin-app
      port: 3000

