---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: access-control-apimanagement-simple-weather
  namespace: apps
  labels:
    subscription: standard
spec:
  openApiSpec:
    path: /openapi.yaml

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: access-control-apimanagement-simple-weather
  namespace: apps
spec:
  groups:
    - external
  apiSelector: # <======== Select all APIs with label subscription=external
    matchLabels:
      subscription: standard

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: access-control-apimanagement-simple-weather
  namespace: apps
  annotations:
    hub.traefik.io/api: access-control-apimanagement-simple-weather
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`api.access-control.apimanagement.docker.localhost`) && PathRegexp(`^/simple/weather(/([0-9]+|openapi.yaml))?$`)
    kind: Rule
    services:
    - name: weather-app
      port: 3000
