---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: neo-secret
  namespace: neo
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: neo-k3d
      versionId: 66481907-98c0-421a-b8fb-e3364d6283d6
