---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: neo-secret
  namespace: neo
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: neo-k3d
      versionId: a769f384-8dc2-46e6-849a-ad952a8880e3
