---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: secure-applications-apigateway-no-auth
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`secure-applications.apigateway.docker.localhost`) && Path(`/no-auth`)
    kind: Rule
    services:
    - name: whoami
      port: 80
