---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: neo-k3d
  namespace: pop
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: neo-k3d
      versionId: 8def658d-a9fd-42c2-b58e-18e7d1eb7d78
