apiVersion: hub.traefik.io/v1alpha1
kind: APIPortal
metadata:
  name: my-portal
spec:
  title: "Awesome Portal"
  description: "This is an awesome portal."
  customDomains:
    - my-portal.tls.docker.localhost

  apiGateway: my-gateway
