# Default values for hub-helm-chart.
image:
  tag: "experimental"
# User token to access to hub
token: "${TOKEN_CLUSTER}"
controllerDeployment:
  args:
    - --log-level=debug
    - --log-format=console
    - --ingress-class-name=traefik-lb
    - --platform-url=http://platform.docker.localhost/agent
    - --traefik.metrics-url=http://traefik-hub.hub-agent.svc.cluster.local:8080/metrics
tunnelDeployment:
  args:
    - --log-level=debug
    - --platform-url=http://platform.docker.localhost/agent
