---
apiVersion: v1
kind: Namespace
metadata:
  name: hydra

---
apiVersion: v1
kind: Secret
metadata:
  name: hydra
  namespace: hydra
type: Opaque
stringData:
  DSN: memory
  SECRETS_SYSTEM: youReallyNeedToChangeThis
  SECRETS_COOKIE: youReallyNeedToChangeThis
  OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: youReallyNeedToChangeThis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: migrate
          image: docker.io/oryd/hydra:v2.2.0
          args:
            - migrate
            - sql
            - -e
            - --yes
          envFrom:
            - secretRef:
                name: hydra
                optional: false
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      containers:
        - name: hydra
          image: docker.io/oryd/hydra:v2.2.0
          args:
            - serve
            - all
            - --dev
          envFrom:
            - secretRef:
                name: hydra
                optional: false
          env:
            - name: URLS_SELF_ISSUER
              value: http://hydra.hydra.svc:4444
            - name: URLS_SELF_ADMIN
              value: http://hydra.hydra.svc:4445
            - name: URLS_SELF_PUBLIC
              value: http://hydra.docker.localhost
            - name: URLS_CONSENT
              value: http://consent.docker.localhost/consent
            - name: URLS_LOGIN
              value: http://consent.docker.localhost/login
            - name: URLS_LOGOUT
              value: http://consent.docker.localhost/logout
            - name: STRATEGIES_ACCESS_TOKEN
              value: jwt
            - name: WEBFINGER_OIDC_DISCOVERY_TOKEN_URL
              value: http://hydra.hydra.svc:4444/oauth2/token
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          ports:
            - containerPort: 4444
              name: public
              protocol: TCP
            - containerPort: 4445
              name: admin
              protocol: TCP
            - containerPort: 5555
              name: token
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 800m
              memory: 392Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hydra
  namespace: hydra
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: public
      name: public
    - port: 4445
      targetPort: admin
      name: admin
    - port: 5555
      targetPort: token
      name: token
  selector:
    app: hydra

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hydra
  namespace: hydra
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`hydra.docker.localhost`)
    kind: Rule
    services:
    - name: hydra
      port: public

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent
  namespace: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consent
  template:
    metadata:
      labels:
        app: consent
    spec:
      automountServiceAccountToken: false
      containers:
        - name: consent
          image: docker.io/jlevesy/hail-hydra:v0.0.1
          args:
            - -a
            - http://hydra.hydra.svc:4445
            - -b
            - :3000
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          ports:
            - containerPort: 3000
              name: consent
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: consent
  namespace: hydra
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: consent
      name: consent
  selector:
    app: consent

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: consent
  namespace: hydra
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`consent.docker.localhost`)
    kind: Rule
    services:
    - name: consent
      port: consent

