---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-app-forecast-data
  namespace: apps
data:
  api.json: |
    {
      "weather": {
        "1":  { "city": "GopherCity", "weather": "Cloudy", "dt": "3128231402" },
        "2":  { "city": "City of Gopher", "weather": "Rainy", "dt": "3128231402" },
        "3":  { "code": "GopherCentral", "weather": "Shiny", "dt": "3128231402" }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-forecast
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app-forecast
  template:
    metadata:
      labels:
        app: weather-app-forecast
    spec:
      containers:
        - name: api
          image: ghcr.io/traefik/api-server:v1.0.0
          args: ["-data", "/api/api.json", "-errorrate", "2"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: api-data
            mountPath: /api
      volumes:
        - name: api-data
          configMap:
            name: weather-app-forecast-data

---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-forecast
  namespace: apps
  labels:
    app: weather-app-forecast
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: weather-app-forecast
