---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik
          image: traefik:v2.9
          args:
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.websecure.http.tls=true
            - --entrypoints.cluster-proxy.Address=:9090
            - --providers.kubernetescrd.allowexternalnameservices=true
            - --providers.kubernetescrd.allowcrossnamespace=true
            - --providers.kubernetesingress.ingressclass=traefik-lb
            - --api.dashboard
            - --api.insecure
            - --metrics.prometheus
            - --log.level=debug

            - --experimental.hub
            - --hub.tls.insecure
            - --metrics.prometheus.addrouterslabels
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: cluster-proxy
              containerPort: 9090
            - name: metrics
              containerPort: 8080
