{
 "title": "Neo",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(http_current_connections, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_current_connections, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request bytes by handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(http_response_bytes_sum{service=~\"$service\", namespace=~\"$namespace\"} / http_response_bytes_count{service=~\"$service\", namespace=~\"$namespace\"}) by (service, handler)",
     "legendFormat": "{{service}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Request duration by handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds_sum{service=~\"$service\", namespace=~\"$namespace\"} / http_request_duration_seconds_count{service=~\"$service\", namespace=~\"$namespace\"}) by (handler, service)",
     "legendFormat": "{{service}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=~\"$service\", namespace=~\"$namespace\"}[5m])) by (service,handler)",
     "legendFormat": "{{service}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_current_connections{service=~\"$service\", namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Errors Percent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{code!~\"200|201|202|203|204\", service=~\"$service\", namespace=~\"$namespace\"}) by (service) / sum(http_request_duration_seconds_count{code=~\"200|201|202|203|204\", service=~\"$service\", namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}