---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: api-lifecycle-apimanagement-weather-api-v1-1
  namespace: apps
spec:
  release: v1.1.0

---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: api-lifecycle-apimanagement-weather-api-v1-1
  namespace: apps
spec:
  versions:
    - name: api-lifecycle-apimanagement-weather-api-v1
    - name: api-lifecycle-apimanagement-weather-api-v1-1

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: api-lifecycle-apimanagement-weather-api-v1-1
  namespace: apps
spec:
  apis:
  - name: api-lifecycle-apimanagement-weather-api-v1-1
  everyone: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-lifecycle-apimanagement-weather-api-v1-1
  namespace: apps
  annotations:
    hub.traefik.io/api-version: api-lifecycle-apimanagement-weather-api-v1
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.lifecycle.apimanagement.docker.localhost`) && Path(`/weather-multi-versions`)
    kind: Rule
    services:
    - name: weather-app
      port: 3000

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-lifecycle-apimanagement-weather-api-v1-1-preview
  namespace: apps
  annotations:
    hub.traefik.io/api-version: api-lifecycle-apimanagement-weather-api-v1-1
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.lifecycle.apimanagement.docker.localhost`) && Path(`/weather-multi-versions`) && Header(`X-Version`, `preview`)
    kind: Rule
    services:
    - name: weather-app-forecast
      port: 3000
