---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: api-lifecycle-apimanagement-weather-api-wrr
  namespace: apps
spec:
  weighted:
    services:
      - name: weather-app
        port: 3000
        weight: 1
      - name: weather-app-forecast
        port: 3000
        weight: 1

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-api
  namespace: apps
  annotations:
    hub.traefik.io/api-version: api-lifecycle-apimanagement-weather-api-v1-1
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.lifecycle.apimanagement.docker.localhost`) && PathPrefix(`/weather-v1-wrr`)
    kind: Rule
    services:
    - name: api-lifecycle-apimanagement-weather-api-wrr
      port: 3000
      kind: TraefikService
    middlewares:
      - name: stripprefix-weather
