---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: api-lifecycle-apimanagement-weather-api
  namespace: apps
spec: {}

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: api-lifecycle-apimanagement-weather-api
  namespace: apps
spec:
  apis:
  - name: api-lifecycle-apimanagement-weather-api
  everyone: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-lifecycle-apimanagement-weather-api
  namespace: apps
  annotations:
    hub.traefik.io/api: api-lifecycle-apimanagement-weather-api # <=== Link to the API using its name
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.lifecycle.apimanagement.docker.localhost`) && Path(`/weather`)
    kind: Rule
    services:
    - name: weather-app
      port: 3000
