---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-cluster
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-cluster
  template:
    metadata:
      labels:
        app: hub-cluster
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-cluster
          image: gcr.io/traefiklabs/hub-cluster:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: API_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  key: public.out
                  name: api-token-key
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: hub-secret
            - name: JWT_ISS
              value: "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name: JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: hub-secret
            - name: OFFER_SERVICE_URL
              value: http://hub-offer.hub.svc.cluster.local/internal
            - name: ACP_SERVICE_URL
              value: http://hub-acp.hub.svc.cluster.local/internal
            - name: ALERT_SERVICE_URL
              value: http://hub-alert.hub.svc.cluster.local/internal
            - name: API_MANAGEMENT_SERVICE_URL
              value: http://hub-api-management.hub.svc.cluster.local/internal
            - name: WORKSPACE_SERVICE_URL
              value: http://hub-workspace.hub.svc.cluster.local/internal
            - name: METRICS_SERVICE_URL
              value: http://hub-metrics.hub.svc.cluster.local/internal
            - name: TOKEN_SERVICE_URL
              value: http://hub-token.hub.svc.cluster.local/internal
            - name: TOPOLOGY_SERVICE_URL
              value: http://hub-topology.hub.svc.cluster.local/internal
            - name: GSLB_SERVICE_URL
              value: http://hub-gslb.hub.svc.cluster.local/internal
            - name: TUNNEL_SERVICE_URL
              value: http://hub-tunnel-orchestrator.hub.svc.cluster.local/internal
            - name: NOTIFICATION_SERVICE_URL
              value: http://hub-notification.hub.svc.cluster.local/internal
            - name: TRACE_SERVICE_URL
              value: http://hub-trace.hub.svc.cluster.local/internal
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: MAX_MIND_ACCOUNT_ID
              value: ""
            - name: MAX_MIND_LICENSE_KEY
              value: ""
            - name: MONGODB_URI
              value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/clusters?authSource=admin
            - name: LOG_LEVEL
              value: debug
          args:
            - serve
            - --addr=:80
---
apiVersion: v1
kind: Service
metadata:
  name: hub-cluster
  namespace: hub
  labels:
    app: hub-cluster
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-cluster
    - port: 40000
      targetPort: 40000
      name: hub-cluster-debug
  selector:
    app: hub-cluster

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster-agent-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && (Path(`/agent/link`) || Path(`/agent/ping`) || Path(`/agent/version-status`))
      services:
        - name: hub-cluster
          port: 80
      middlewares:
        - name: auth-token
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster-agent
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && (Path(`/agent/link`) || Path(`/agent/ping`) || Path(`/agent/version-status`))
      services:
        - name: hub-cluster
          port: 80
      middlewares:
        - name: auth-token

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/cluster/external`)
      services:
        - name: hub-cluster
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/cluster/external`)
      services:
        - name: hub-cluster
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/cluster/internal`)
      services:
        - name: hub-cluster
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cluster-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/cluster/internal`)
      services:
        - name: hub-cluster
          port: 80
      middlewares:
        - name: stripprefix
