---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-user
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-user
  template:
    metadata:
      labels:
        app: hub-user
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-user
          image: gcr.io/traefiklabs/hub-user:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: hub-secret
            - name: JWT_ISS
              value: "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name: JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: hub-secret
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: LOG_LEVEL
              value: debug
            - name: MONGODB_URI
              value: "mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/user?authSource=admin"
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: hub-services-client-id
                  name: hub-secret
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: hub-services-client-secret
                  name: hub-secret
            - name: AUTH0_ENDPOINT
              value: https://traefiklabs-hub-preview.eu.auth0.com
            - name: AUTH0_AUDIENCE
              value: https://traefiklabs-hub-preview.eu.auth0.com/api/v2/
            - name: TRACE_SERVICE_URL
              value: http://hub-trace.hub.svc.cluster.local/internal
          args:
            - serve
            - --addr=:80

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hub-user-delete
  namespace: hub
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      parallelism: 1
      template:
        metadata:
          labels:
            cronjob: hub-user-delete
        spec:
          containers:
            - args:
                - deleteuser
              env:
                - name: ACP_SERVICE_URL
                  value: http://hub-acp.hub.svc.cluster.local/internal
                - name: ALERT_SERVICE_URL
                  value: http://hub-alert.hub.svc.cluster.local/internal
                - name: CATALOG_SERVICE_URL
                  value: http://hub-catalog.hub.svc.cluster.local/internal
                - name: CERTIFICATE_SERVICE_URL
                  value: http://hub-certificates.hub.svc.cluster.local/internal
                - name: CLUSTER_SERVICE_URL
                  value: http://hub-cluster.hub.svc.cluster.local/internal
                - name: GSLB_SERVICE_URL
                  value: http://hub-gslb.hub.svc.cluster.local/internal
                - name: INVITATION_SERVICE_URL
                  value: http://hub-invitation.hub.svc.cluster.local/internal
                - name: METRICS_SERVICE_URL
                  value: http://hub-metrics.hub.svc.cluster.local/internal
                - name: NOTIFICATION_SERVICE_URL
                  value: http://hub-notification.hub.svc.cluster.local/internal
                - name: OFFER_SERVICE_URL
                  value: http://hub-offer.hub.svc.cluster.local/internal
                - name: TOKEN_SERVICE_URL
                  value: http://hub-token.hub.svc.cluster.local/internal
                - name: TOPOLOGY_SERVICE_URL
                  value: http://hub-topology.hub.svc.cluster.local/internal
                - name: TUNNEL_SERVICE_URL
                  value: http://hub-tunnel-orchestrator.hub.svc.cluster.local/internal
                - name: WORKSPACE_SERVICE_URL
                  value: http://hub-workspace.hub.svc.cluster.local/internal
                - name: LOG_LEVEL
                  value: debug
                - name: MONGODB_URI
                  value: "mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/user?authSource=admin"
                - name: AUTH0_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: hub-services-client-id
                      name: hub-secret
                - name: AUTH0_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: hub-services-client-secret
                      name: hub-secret
                - name: AUTH0_ENDPOINT
                  value: https://traefiklabs-hub-preview.eu.auth0.com
                - name: AUTH0_AUDIENCE
                  value: https://traefiklabs-hub-preview.eu.auth0.com/api/v2/
              image: gcr.io/traefiklabs/hub-user:latest
              name: hub-user-delete
          imagePullSecrets:
            - name: gcr-access-token
          restartPolicy: Never
  schedule: '@daily'
  suspend: true

---
apiVersion: v1
kind: Service
metadata:
  name: hub-user
  namespace: hub
  labels:
    app: hub-user
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-user
  selector:
    app: hub-user

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/external`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/external`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/internal`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/internal`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-auth0-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/auth0`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-auth0
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/auth0`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-public-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/public`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-public
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/user/public`)
      services:
        - name: hub-user
          port: 80
      middlewares:
        - name: stripprefix
