---
kind: ConfigMap
apiVersion: v1
metadata:
  name: pebble-ca
  namespace: hub
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDCTCCAfGgAwIBAgIIJOLbes8sTr4wDQYJKoZIhvcNAQELBQAwIDEeMBwGA1UE
    AxMVbWluaWNhIHJvb3QgY2EgMjRlMmRiMCAXDTE3MTIwNjE5NDIxMFoYDzIxMTcx
    MjA2MTk0MjEwWjAgMR4wHAYDVQQDExVtaW5pY2Egcm9vdCBjYSAyNGUyZGIwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5WgZNoVJandj43kkLyU50vzCZ
    alozvdRo3OFiKoDtmqKPNWRNO2hC9AUNxTDJco51Yc42u/WV3fPbbhSznTiOOVtn
    Ajm6iq4I5nZYltGGZetGDOQWr78y2gWY+SG078MuOO2hyDIiKtVc3xiXYA+8Hluu
    9F8KbqSS1h55yxZ9b87eKR+B0zu2ahzBCIHKmKWgc6N13l7aDxxY3D6uq8gtJRU0
    toumyLbdzGcupVvjbjDP11nl07RESDWBLG1/g3ktJvqIa4BWgU2HMh4rND6y8OD3
    Hy3H8MY6CElL+MOCbFJjWqhtOxeFyZZV9q3kYnk9CAuQJKMEGuN4GU6tzhW1AgMB
    AAGjRTBDMA4GA1UdDwEB/wQEAwIChDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
    BQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADANBgkqhkiG9w0BAQsFAAOCAQEAF85v
    d40HK1ouDAtWeO1PbnWfGEmC5Xa478s9ddOd9Clvp2McYzNlAFfM7kdcj6xeiNhF
    WPIfaGAi/QdURSL/6C1KsVDqlFBlTs9zYfh2g0UXGvJtj1maeih7zxFLvet+fqll
    xseM4P9EVJaQxwuK/F78YBt0tCNfivC6JNZMgxKF59h0FBpH70ytUSHXdz7FKwix
    Mfn3qEb9BXSk0Q3prNV5sOV3vgjEtB4THfDxSz9z3+DepVnW3vbbqwEbkXdk3j82
    2muVldgOUgTwK8eT+XdofVdntzU/kzygSAtAQwLJfn51fS1GvEcYGBc1bDryIqmF
    p9BI7gVKtWSZYegicA==
    -----END CERTIFICATE-----

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-certificates
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-certificates
  template:
    metadata:
      labels:
        app: hub-certificates
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-certificates
          image: gcr.io/traefiklabs/hub-certificates:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: config-volume
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: hub-secret
            - name: JWT_ISS
              value: "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name: JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: hub-secret
            - name: RESOLVER_ACCOUNT
              value: ewogICAgIkNBU2VydmVyIjogImh0dHBzOi8vcGViYmxlLnBlYmJsZS5zdmMuY2x1c3Rlci5sb2NhbDoxNDAwMC9kaXIiLAogICAgIkVtYWlsIjogIm5lby1jZXJ0aWZpY2F0ZXNAdHJhZWZpay5pbyIsCiAgICAiUHJpdmF0ZUtleSI6ICJNSUlKSndJQkFBS0NBZ0VBdTRibE00NDBCVlRWdmVkN2RockkvMU8yeUFVdFRucHVMZzlxc3FjWjNBczM4ZE8yUG14TzJzQmtVNU1XSjNmVExXalNmbDBYdTQyRXNVY1lScW9hd1o2R1pvR1BqeU5SNFd2b1JCVzl6NUJZa25iK1Zqem5lVjhzWGUzM0xDTU44T3YwZ3ZJMkpKcEc4eTRQT1VHTDM4aExqYjZCRnhFbmYvM0kvbFRWaGZPQkFtelE2N045MExQZ3o1QlEvR3QrbThnT01NTnRpTllrcnhwM0xvR3ZQd08wV0N4aWRsK05hZi9uaHg3NU1CTjB2TzRqcmNlSG1FbDJZczBoM0c5NzJpNDBjbEJ5ZTM0VVI3WXNPRVQyRWJYbDFEL044SWlqaGZDZGliQmJNUWlCN243c0RwbENmbjNjakMvRFc3Mm9RaW9JOHMwaldMSmM4endzUk9JR2FhMFNIVEVzRm9tWENsZzdrU2psQzJiTWc4NStmejU5KzgrQlRqcCtaaFN5WU1abnRUVXFyT0gxTHV2SzFtZ1VCTXRoZEtTOTZHWitpaG5scG90Q21LU295YjJVaWV0WUlTalV2WWloRUI3bDRqdDFHK1AzWHZGR1M4QVdhQmIreXh4b2p2eTkzUGovRjNmTHhiRmkySmdJejJRU240VlEzdnRaVlAxcVkwbzd0UzJ4TVM2QkU0U2dVQUp5MUV5U1hOSmhVYVI2R1MvWit0c1RwMFVhTVg5OWx1eUtRY3lMRVl6R3E1SnlHSFNiaWVMd2s5aFZBZWM2Z0Q5WGhYUzNmMzhWOGdrc05UU09seWpDS1lSdllYRzlza0huekpzcEVaYWdIVlZobk5idzlnZi9HVG9hZk5JWmFBTUE5UElXaHZYbWN5MmJpK0V5dSthemJ4cHdzbXNDQXdFQUFRS0NBZ0FqajdVdlRhdzN4cHF4NUkvWkdjTThDQmdGWGxYMUorcDArWjkyT1pJQjFHN0xnU1p5Ti8vTUkrZmlvV1gySGhjQjZYcmhVNjRJZHhIT3ZIaXlEZGY5RjU3TkdZeXJ6RHJlMEtPL0paQlZLRDVqcUFVYlBYbDMzc0IvSDMxYjlWblRjaXR3R1phQzRtN0o5dFlVT1lYWTdoYkZ6bmFVZFVCVVdVQWdXdDRUQk5aV0syU0REZ3F4NVNxZ3NmRnByTWpacWRwbkRPaGNwcDlXUldLTWd6TkVjK05qUlNkMjR5L2lCaEZWNGwzRzdDbWJHbDNSdXFEUUZENUxCak9CcGZLS3NYQm9yVERJa21RdUpUSEZpZTVQOVhxY0FXMkFTNmtXNFVZK3NoN1k4WkFTTmlkMXJVS2EwaXRjdWtJRng3Vjh0cFB6MTByNHF2cE5kZisvSUUydXNSeG9GQlhBcm0xRW8ybi9yaUFTakVTVmR3RjZQbFNlZEF3amx2UjJseTF6RmYvcGxOSklTdXkxZm9od05Cd1hRZThaVXE5N09HZmZ6a1h4SzluenFkQ21FMyszbEd4NEhaZ0pLSnFlY2E2VFhxTlExUUljTjZLWDBmL3VnT1doY0hESDB1NVkwcU1LUkxXNmFKN2d6ZXZuNCt6VjJVYTRoZlVSd09LRFVBNVpWNnZycG1kcS93K3hCU1o5Nk5KM20waGIyR0orRlFCL3M3Tko4YXJsL3ViSnZjSUhDTWVtbHc4dDFyYi9lcFAyUGdkd3ZBSE14T1ZvQXdwRmljdW9aTnFyc0c2dTV6UFJLZXZtbHg0YjNFTEx3bXNmS3lhejJtcDliVWhlTEY4MEkwT09pTEhiRHFTdDB2VC9TVlIrRWY1TFRvQTF5M2FGZmR0TWoyWThRUUtDQVFFQThCMUNLRk15bjhvblovUmVURE5OUnJtN2VVYmN2UUd0S00zOXR6Y1ByblQ2Ymc1ejZuVjdFSnYzRlZIOVU4QkE3aHNjTFlxNUQzUWhweXNzY3JXNk5mYzRGNGxSSlU1aExxdVRNdkh6UWZkV2ZJdUxXQTM4Ui9HU0ZKQzE4RVpJVHVLa2JGcHNaUk1PakhqUFNBbWdJNFVabWxQOWpKSXJXY3F4NVBVdnRTOGlwMEk0T0lIdndtSHFONktiUXhVTkl4aHJiL0ZhdzI3bWN2ZTFxWkQ3bVprTG9OYUc1QXdjdHloVXN6cHRacDhJb21vSUorMzdIUEFpV1U1cGdjZVcyVmVwVkxTRzhiTlZDUXJtZ1AzVlZDeWdlQjJGdUwxb2hXMXJCNVJ3QnB6SGdWTWpNRUFaYXRJRGNBMDZIdzBsTm1SUEVDTGRUTG5ob2RkUHEvNzJXUUtDQVFFQXgrNzdLSWdMbjYvOE9EeVdvNjZ1SWp2SGhIT0NpbWhhQWdYTWlRdVIwRExPZ05NMUtpb3NCbmp1Y0pld2g2eHZTU25GRzNwcXY3TlFBOThuYXN4U25STktpZjRqMTZ0bG9WWVltMC9pVzAzYTBjN01ISFFjMWxmSSs3S0NHUjkwd01uaTZFSTlZL2lmWUgwL3h0Y0IrZEIyN0tvK3BJYWk1QmxsUW1Ra1NVdFVCMFhLQjlBbFd3ZkVzWWM5bFRrVWFDM1BNNmw4YjVRWkJFU0h5dzl3TWtHakE1eVBsOXZUL0U2NlNJQWhWejhsTFNEUVZjeHdNeUpONTZMdGp6Y05kNThncmYzcVNiaTZPQ3BHS2llVCtmLzQ0VXV2cE1BM3dHY3ZZakxIWHV6dVNqTk1ZZ0hjUkJvUTgzWGQ5WHR0cE9NczFTT1A3NWdQZlBSTUNLRWVZd0tDQVFBSlF4ZXFOb3RkWG83bWs2YVBpZXNSTDFqcjlLL1BHcUZ6VVg3WDhtZkljdnEyQkJpMGtwT01zSGQzZXhJcWlOLzRUMU5tN2xMMUphV21yU09weVJqRnZDT054TjQ4Y2ltTmcxREtSa3I3NEc2Vm4weGd1U2xpSFE5bGU2K0k5UzBVM2VrNXhNTXBvdktNdUp4R1N4akNSZ0FXMCthVDVZK0doeXNWaWQrdFBZUTRyM1U3dU1kbTJDQVF4VlQzNFhnQVFwRGlZSXovdk9kbXgrZGFBeDJ4YnhYanZtSzFxVUh5VHJ2MXJldEthaGdMSzh2a3ZtbFJWSEgrditlUitnRDNvVW9HMm0vYUl2REV5SWJic3U3bnNGRUFVU00zWFJjTERvMXlYV2QwMmRkWVJieTF2OE03TzU2bVU5eEtGbGU1SVdWcldlenZhTHdyWWdMUXY2VUJBb0lCQUJvOStlVldCZ0NOdnRNNjBLTG5XSi9Sck54cnRPU3AwYmFXUUVSMHFrempma3RXYlpIOU93NFdiV1dGNDN2TFhFZ0VIWVQveW1jakNBdWFETGh0M1NJVTJDSElvN2U1SFh2UnF5VW5sUlJhNGEvTUx1cEZLMHZPOWVoamc4UDhadnl2QXdOdFBsV1Myb2gxcUJ0WE9VRXE1WkVtdjFZay9kaG1wTzNUNnhkYnRjbkdsVC8xU0JIc3NScUVIOGNvV005YncraUtCSFU0d1JmWVR1S09RakcyZjhrSGthbGpCeTRFdjFxb3hyZUc2RUJHSUZKQ3BTOXcvenk2RytoQ1Y1Z3Q0TUkxbzd6TmJGUFc2S0s3MHlaclBLV0ZvNlpDUEk4YWZCT3RpcEdoRTUzVm9kN3pVNC8wdytqUXZiTnM0ZlZVaEJ2dHNRVEh0ckMxK0F6aDZQVUNnZ0VBUEgvMHFFTnBCM1I4R1oyUGpZbExIa1VpQlVvRzRiTFBPRXNiV2ZtdUd0Mnh0dlhqUDdwcDBhSjBuYzdHUVBOc3VVY0dZbEgrSW1aaUpsUy9yWkE0WjloYzk3cVZ5YkRzUWxTWDdUZXp6UmJweFNrN0NkWElZMkRwWUt1NEZCQnU0U3czTEw5QWxlLzVsU0JuNGdBUlMyQ1JOSndGaTNuSGl6c2phWXIxV3lTVy8yWWdSeDRGZ0EwQWRyYnNEb0oxMGQrZk1XRkVpMFdqRXNlVnlaSDJRQTY0RFlkNEFzMXIwSUo2SC9ZSytobzlxSVU0THhieERYUFZSeFBHNnpUQ3FUdUswYXJSVnZCRWtOdEJuTFh1L09RQ2pjV3d0QXJNWWs4dW1jWVd2eURtSjRYMWdVZkp0WC85dHJnY0VEWDM3VEFwREZFSnUzTkNUMTR6bGNETXlRPT0iCn0=
            - name: LEGO_CA_CERTIFICATES
              value: /config/ca.pem
            - name: LEGO_CA_SERVER_NAME
              value: pebble
            - name: MONGODB_URI
              value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/certifications?authSource=admin
            - name: MONGODB_ENCRYPTION_KEY
              value: JUMqRi1KYU5jUmZValhuMnI1dTh4L0E/RChHK0tiUGU=
            - name: LOG_LEVEL
              value: debug
            - name: GSLB_SERVICE_URL
              value: http://hub-gslb.hub.svc.cluster.local/internal
            - name: NOTIFICATION_SERVICE_URL
              value: http://hub-notification.hub.svc.cluster.local/internal
            - name: WORKSPACE_SERVICE_URL
              value: http://hub-workspace.hub.svc.cluster.local/internal
            - name: HUB_DOMAIN_SUFFIX
              value: hub.traefik.io
            - name: CLOUDFLARE_EMAIL
              value: "email"
            - name: CLOUDFLARE_TOKEN
              value: token
            - name: CLOUDFLARE_KEY
              value: "key"
            - name: DEV_MODE
              value: "true"
          args:
            - serve
            - --addr=:80
      volumes:
        - name: config-volume
          configMap:
            name: pebble-ca
---
apiVersion: v1
kind: Service
metadata:
  name: hub-certificates
  namespace: hub
  labels:
    app: hub-certificates
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-certificates
    - port: 443
      targetPort: 443
      name: hub-certificates-challenges
  selector:
    app: hub-certificates

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: certificates-agent
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && Path(`/agent/wildcard-certificate`)
      services:
        - name: hub-certificates
          port: 80
      middlewares:
        - name: auth-token

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: certificates-agent-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && Path(`/agent/wildcard-certificate`)
      services:
        - name: hub-certificates
          port: 80
      middlewares:
        - name: auth-token
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: certificates-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/certificates/external`)
      services:
        - name: hub-certificates
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: certificates-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/certificates/external`)
      services:
        - name: hub-certificates
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: certificates-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/certificates/internal`)
      services:
        - name: hub-certificates
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: certificates-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/certificates/internal`)
      services:
        - name: hub-certificates
          port: 80
      middlewares:
        - name: stripprefix
