---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-workspace
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-workspace
  template:
    metadata:
      labels:
        app: hub-workspace
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-workspace
          image: gcr.io/traefiklabs/hub-workspace:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: hub-secret
            - name: JWT_ISS
              value: "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name: JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: hub-secret
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_USERNAME
              value: jaeger
            - name: TRACING_PASSWORD
              value: "jaeger"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: OFFER_SERVICE_URL
              value: "http://hub-offer.hub.svc.cluster.local/internal"
            - name: API_MANAGEMENT_SERVICE_URL
              value: "http://hub-api-management.hub.svc.cluster.local/internal"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://hub-notification.hub.svc.cluster.local/internal"
            - name: USER_SERVICE_URL
              value: "http://hub-user.hub.svc.cluster.local/internal"
            - name: TRACE_SERVICE_URL
              value: http://hub-trace.hub.svc.cluster.local/internal
            - name: MONGODB_ENCRYPTION_KEY
              value: JUMqRi1KYU5jUmZValhuMnI1dTh4L0E/RChHK0tiUGU=
            - name: MONGODB_URI
              value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/workspaces?authSource=admin
            - name: HUB_DOMAIN_SUFFIX
              value: traefik-hub.app
            - name: LOG_LEVEL
              value: debug
            - name: LOG_FORMAT
              value: console
          args:
            - serve
            - --addr=:80
---
apiVersion: v1
kind: Service
metadata:
  name: hub-workspace
  namespace: hub
  labels:
    app: hub-workspace
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-workspace
    - port: 40000
      targetPort: 40000
      name: hub-workspace-debug
  selector:
    app: hub-workspace

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workspace-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/workspace/external`)
      services:
        - name: hub-workspace
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workspace-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/workspace/external`)
      services:
        - name: hub-workspace
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workspace-auth0-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/workspace/auth0`)
      services:
        - name: hub-workspace
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workspace-auth0
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/workspace/auth0`)
      services:
        - name: hub-workspace
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workspace-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/workspace/internal`)
      services:
        - name: hub-workspace
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workspace-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/workspace/internal`)
      services:
        - name: hub-workspace
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workspace-agent
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && Path(`/agent/workspaces/ca/sign`)
      services:
        - name: hub-workspace
          port: 80
      middlewares:
        - name: auth-token
