---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-api-management
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-api-management
  template:
    metadata:
      labels:
        app: hub-api-management
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-api-management
          image: gcr.io/traefiklabs/hub-api-management:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name : JWT_CERT
              valueFrom :
                secretKeyRef :
                  key : jwt-cert
                  name : hub-secret
            - name : JWT_ISS
              value : "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name : JWT_SUB
              valueFrom :
                secretKeyRef :
                  key : jwt-sub
                  name : hub-secret
            - name: MONGODB_URI
              value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/apimanagement?authSource=admin
            - name: MONGODB_ENCRYPTION_KEY
              value: JUMqRi1KYU5jUmZValhuMnI1dTh4L0E/RChHK0tiUGU=
            - name: HYDRA_URL
              value: http://hydra.hydra.svc.cluster.local:4445
            - name: HYDRA_ISSUER_URL
              value: http://sso.portal.docker.localhost
            - name: OFFER_SERVICE_URL
              value: "http://hub-offer.hub.svc.cluster.local/internal"
            - name: TUNNEL_SERVICE_URL
              value: "http://hub-tunnel-orchestrator.hub.svc.cluster.local/internal"
            - name: WORKSPACE_SERVICE_URL
              value: http://hub-workspace.hub.svc.cluster.local/internal
            - name: CERTIFICATES_SERVICE_URL
              value: "http://hub-certificates.hub.svc.cluster.local/internal"
            - name: TRACE_SERVICE_URL
              value: http://hub-trace.hub.svc.cluster.local/internal
            - name: MQ_URL
              value: nats://traefik-hub:traefik-hub@nats.nats.svc.cluster.local:4222
            - name: LOG_LEVEL
              value: debug
            - name: LOG_FORMAT
              value: console
          args:
            - serve
            - --addr=:80
---
apiVersion: v1
kind: Service
metadata:
  name: hub-api-management
  namespace: hub
  labels:
    app: hub-api-management
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-api-management
    - port: 40000
      targetPort: 40000
      name: hub-api-management-debug
  selector:
    app: hub-api-management

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-agent-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && (PathPrefix(`/agent/gateways`) || PathPrefix(`/agent/portals`) || PathPrefix(`/agent/apis`) || PathPrefix(`/agent/collections`) || PathPrefix(`/agent/accesses`) || PathPrefix(`/agent/users`) || PathPrefix(`/agent/rate-limits`) || PathPrefix(`/agent/versions`) || PathPrefix(`/agent/identity-provider`))
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: auth-token
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-agent
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && (PathPrefix(`/agent/gateways`) || PathPrefix(`/agent/portals`) || PathPrefix(`/agent/apis`) || PathPrefix(`/agent/collections`) || PathPrefix(`/agent/accesses`) || PathPrefix(`/agent/users`) || PathPrefix(`/agent/rate-limits`) || PathPrefix(`/agent/versions`) || PathPrefix(`/agent/identity-provider`))
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: auth-token

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/api-management/external`)
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/api-management/external`)
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-sso-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sso.portal.docker.localhost`) && (PathPrefix(`/login`) || PathPrefix(`/consent`) || PathPrefix(`/error`) || PathPrefix(`/reset-password`) || PathPrefix(`/static`) || PathPrefix(`/robots.txt`))
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: sso-prefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-sso-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`sso.portal.docker.localhost`) && (PathPrefix(`/login`) || PathPrefix(`/consent`) || PathPrefix(`/error`) || PathPrefix(`/reset-password`) || PathPrefix(`/static`) || PathPrefix(`/robots.txt`))
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: sso-prefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/api-management/internal`)
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-management-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/api-management/internal`)
      services:
        - name: hub-api-management
          port: 80
      middlewares:
        - name: stripprefix
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hub-api-management-reconcile-job
  namespace: hub
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      parallelism: 1
      template:
        metadata:
          labels:
            cronjob: hub-api-management-reconcile-job
        spec:
          containers:
            - args:
                - reconcile
              env:
                - name: DRY_RUN
                  value: "false"
                - name: LOG_LEVEL
                  value: debug
                - name: LOG_FORMAT
                  value: console
                - name: MONGODB_URI
                  value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/apimanagement?authSource=admin
                - name: MONGODB_MINPOOL
                  value: "1"
                - name: MONGODB_MAXPOOL
                  value: "3"
                - name: HYDRA_URL
                  value: http://hydra.hydra.svc.cluster.local:4445
                - name: BATCH_SIZE
                  value: "100"
              image: gcr.io/traefiklabs/hub-api-management:latest
              name: hub-api-management-reconcile-job
          imagePullSecrets:
            - name: gcr-access-token
          restartPolicy: Never
  schedule: '@daily'

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hub-api-management-check-unverified-job
  namespace: hub
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      parallelism: 1
      template:
        metadata:
          labels:
            cronjob: hub-api-management-check-job
        spec:
          containers:
            - args:
                - check
              env:
                - name: DEV_MODE
                  value: "true"
                - name: MONGODB_URI
                  value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/apimanagement?authSource=admin
                - name: MONGODB_MINPOOL
                  value: "1"
                - name: MONGODB_MAXPOOL
                  value: "3"
                - name: MONGODB_ENCRYPTION_KEY
                  value: JUMqRi1KYU5jUmZValhuMnI1dTh4L0E/RChHK0tiUGU=
                - name: CERTIFICATES_SERVICE_URL
                  value: "http://hub-certificates.hub.svc.cluster.local/internal"
                - name: HYDRA_URL
                  value: http://hydra.hydra.svc.cluster.local:4445
                - name: LOG_LEVEL
                  value: debug
                - name: LOG_FORMAT
                  value: console
                - name: CNAME_DNS_CHALLENGE
                  value: "acme-challenge.preview.traefikhub.dev"
              image: gcr.io/traefiklabs/hub-api-management:latest
              name: hub-api-management-check-job
          imagePullSecrets:
            - name: gcr-access-token
          restartPolicy: Never
  schedule: '*/1 * * * *'

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hub-api-management-check-verified-job
  namespace: hub
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      parallelism: 1
      template:
        metadata:
          labels:
            cronjob: hub-api-management-check-job
        spec:
          containers:
            - args:
                - check
              env:
                - name: VERIFIED_DOMAIN
                  value: "true"
                - name: DEV_MODE
                  value: "true"
                - name: MONGODB_URI
                  value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/apimanagement?authSource=admin
                - name: MONGODB_MINPOOL
                  value: "1"
                - name: MONGODB_MAXPOOL
                  value: "3"
                - name: MONGODB_ENCRYPTION_KEY
                  value: JUMqRi1KYU5jUmZValhuMnI1dTh4L0E/RChHK0tiUGU=
                - name: CERTIFICATES_SERVICE_URL
                  value: "http://hub-certificates.hub.svc.cluster.local/internal"
                - name: HYDRA_URL
                  value: http://hydra.hydra.svc.cluster.local:4445
                - name: LOG_LEVEL
                  value: debug
                - name: LOG_FORMAT
                  value: console
                - name: CNAME_DNS_CHALLENGE
                  value: "acme-challenge.preview.traefikhub.dev"

              image: gcr.io/traefiklabs/hub-api-management:latest
              name: hub-api-management-check-job
          imagePullSecrets:
            - name: gcr-access-token
          restartPolicy: Never
  schedule: '@daily'
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hub-api-management-sync-idp-job
  namespace: hub
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      parallelism: 1
      template:
        metadata:
          labels:
            cronjob: hub-api-management-sync-idp-job
        spec:
          containers:
            - args:
                - sync-idps
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: LOG_FORMAT
                  value: console
                - name: MONGODB_URI
                  value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/apimanagement?authSource=admin
                - name: MONGODB_MINPOOL
                  value: "1"
                - name: MONGODB_MAXPOOL
                  value: "3"
                - name: MQ_URL
                  value: nats://traefik-hub:traefik-hub@nats.nats.svc.cluster.local:4222
              image: gcr.io/traefiklabs/hub-api-management:latest
              name: hub-api-management-sync-idp-job
          imagePullSecrets:
            - name: gcr-access-token
          restartPolicy: Never
  schedule: '@hourly'
