---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-alert
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-alert
  template:
    metadata:
      labels:
        app: hub-alert
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-alert
          image: gcr.io/traefiklabs/hub-alert:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: CLUSTER_SERVICE_URL
              value: "http://hub-cluster.hub.svc.cluster.local/internal"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://hub-notification.hub.svc.cluster.local/internal"
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: hub-secret
            - name: JWT_ISS
              value: "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name: JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: hub-secret
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: LOG_LEVEL
              value: debug
          args:
            - serve
            - --addr=:80
            - --mongodb-uri=mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/alerts?authSource=admin

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hub-alert-check-job
  namespace: hub
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            app: hub-alert-check-job
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: gcr-access-token
          containers:
            - name: hub-alert-check-job
              image: gcr.io/traefiklabs/hub-alert:latest
              env:
                - name: CLUSTER_SERVICE_URL
                  value: "http://hub-cluster.hub.svc.cluster.local/internal"
              args:
                - check
                - --mongodb-uri=mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/alerts?authSource=admin
                - --cluster-limit=100
                - agent-health
              resources:
                limits:
                  cpu: 50m
                  memory: 32Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hub-alert
  namespace: hub
  labels:
    app: hub-alert
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-alert
  selector:
    app: hub-alert

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alert-agent-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && (Path(`/agent/rules`) || Path(`/agent/notify`) || Path(`/agent/preflight`))
      services:
        - name: hub-alert
          port: 80
      middlewares:
        - name: auth-token
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alert-agent
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && (Path(`/agent/rules`) || Path(`/agent/notify`) || Path(`/agent/preflight`))
      services:
        - name: hub-alert
          port: 80
      middlewares:
        - name: auth-token

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alert-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/alert/external`)
      services:
        - name: hub-alert
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alert-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/alert/external`)
      services:
        - name: hub-alert
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alert-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/alert/internal`)
      services:
        - name: hub-alert
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alert-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/alert/internal`)
      services:
        - name: hub-alert
          port: 80
      middlewares:
        - name: stripprefix
