---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-invitation
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-invitation
  template:
    metadata:
      labels:
        app: hub-invitation
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-invitation
          image: gcr.io/traefiklabs/hub-invitation:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: hub-secret
            - name: JWT_ISS
              value: "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name: JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: hub-secret
            - name: WORKSPACE_SERVICE_URL
              value: http://hub-workspace.hub.svc.cluster.local/internal
            - name: NOTIFICATION_SERVICE_URL
              value: http://hub-notification.hub.svc.cluster.local/internal
            - name: USER_SERVICE_URL
              value: http://hub-user.hub.svc.cluster.local/internal
            - name: INVITATION_LINK_BASE_URL
              value: https://webapp.docker.io/r
            - name: MONGODB_URI
              value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/invitations?authSource=admin
            - name: TRACE_SERVICE_URL
              value: http://hub-trace.hub.svc.cluster.local/internal
            - name: LOG_LEVEL
              value: debug
            - name: LOG_FORMAT
              value: console
          args:
            - serve
            - --addr=:80
---
apiVersion: v1
kind: Service
metadata:
  name: hub-invitation
  namespace: hub
  labels:
    app: hub-invitation
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-invitation
  selector:
    app: hub-invitation
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: invitation-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/invitation/external`)
      services:
        - name: hub-invitation
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: invitation-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/invitation/external`)
      services:
        - name: hub-invitation
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: invitation-auth0
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/invitation/auth0`)
      services:
        - name: hub-invitation
          port: 80
      middlewares:
        - name: stripprefix
