---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-topology-indexer
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-topology-indexer
  template:
    metadata:
      labels:
        app: hub-topology-indexer
        version: "v1"
        k8s-app: hub-topology-indexer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-topology-indexer
          image: gcr.io/traefiklabs/hub-topology:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: CLUSTER_SERVICE_URL
              value: http://hub-cluster.hub.svc.cluster.local/internal
            - name: GITEA_URL
              valueFrom:
                secretKeyRef:
                  name: gitea
                  key: url
            - name: GITEA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea
                  key: token
            - name: GITEA_ORG
              valueFrom:
                secretKeyRef:
                  name: gitea
                  key: org
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: MONGODB_URI
              value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/topologies?authSource=admin
            - name: LOG_LEVEL
              value: debug
          args:
            - index
            - --addr=:80
---
apiVersion: v1
kind: Service
metadata:
  name: hub-topology-indexer
  namespace: hub
  labels:
    app: hub-topology-indexer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-topology-indexer
    - port: 40000
      targetPort: 40000
      name: hub-topology-indexer-debug
  selector:
    app: hub-topology-indexer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: topology-indexer-agent
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && Path(`/agent/index`)
      services:
        - name: hub-topology-indexer
          port: 80
      middlewares:
        - name: auth-token

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: topology-indexer-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/topology-indexer/internal`)
      services:
        - name: hub-topology-indexer
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: topology-indexer-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/topology-indexer/internal`)
      services:
        - name: hub-topology-indexer
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default
