---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-catalog
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-catalog
  template:
    metadata:
      labels:
        app: hub-catalog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-catalog
          image: gcr.io/traefiklabs/hub-catalog:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name : JWT_CERT
              valueFrom :
                secretKeyRef :
                  key : jwt-cert
                  name : hub-secret
            - name : JWT_ISS
              value : "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name : JWT_SUB
              valueFrom :
                secretKeyRef :
                  key : jwt-sub
                  name : hub-secret
            - name: MONGODB_URI
              value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/tokens?authSource=admin
            - name: OFFER_SERVICE_URL
              value: "http://hub-offer.hub.svc.cluster.local/internal"
            - name: TUNNEL_SERVICE_URL
              value: "http://hub-tunnel-orchestrator.hub.svc.cluster.local/internal"
            - name: WORKSPACE_SERVICE_URL
              value: http://hub-workspace.hub.svc.cluster.local/internal
            - name: CERTIFICATES_SERVICE_URL
              value: "http://hub-certificates.hub.svc.cluster.local/internal"
            - name: EVENTS_SERVICE_URL
              value: http://hub-log-events.hub.svc.cluster.local/internal
            - name: LOG_LEVEL
              value: debug
          args:
            - serve
            - --addr=:80
---
apiVersion: v1
kind: Service
metadata:
  name: hub-catalog
  namespace: hub
  labels:
    app: hub-catalog
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-catalog
    - port: 40000
      targetPort: 40000
      name: hub-catalog-debug
  selector:
    app: hub-catalog

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: catalog-agent-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/agent/catalogs`)
      services:
        - name: hub-catalog
          port: 80
      middlewares:
        - name: auth-token
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: catalog-agent
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/agent/catalogs`)
      services:
        - name: hub-catalog
          port: 80
      middlewares:
        - name: auth-token
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: catalog-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/catalog/external`)
      services:
        - name: hub-catalog
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: catalog-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/catalog/external`)
      services:
        - name: hub-catalog
          port: 80
      middlewares:
        - name: stripprefix
