---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-token
  namespace: hub
spec:
  forwardAuth:
    address: http://hub-token.hub.svc.cluster.local:80/internal/verify-token
    authResponseHeaders:
      - Workspace-Id
      - Cluster-Id

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: push-indexer-prefix
  namespace: hub
spec:
  addPrefix:
    prefix: /agent/git

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: hub
spec:
  stripPrefix:
    prefixes:
      - /acp
      - /alert
      - /broker
      - /certificates
      - /check
      - /cluster
      - /gslb
      - /invitation
      - /metrics
      - /notification
      - /offer
      - /user
      - /token
      - /topology-indexer-api # the order of strip prefixes is important ! :-/
      - /topology
      - /tunnel
      - /workspace

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: git-strip-prefix
  namespace: hub
spec:
  stripPrefix:
    prefixes:
      - /traefiklabs

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: git-token
  namespace: hub
spec:
  headers:
    customRequestHeaders:
      Authorization: Basic aHViOmh1Yg==

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: hub
spec:
  forwardAuth:
    address: http://hub-topology.hub.svc.cluster.local:80/internal/auth

