---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: hub-k3d
  namespace: pop
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: hub-k3d
      versionId: 9298563f-fb0c-4b68-8351-9d25b39fe3b6
