---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: hub-k3d
  namespace: pop
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: hub-k3d
      versionId: 25c80db1-742e-4d0e-8ba8-0fd86af487ec
