---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: hub-k3d
  namespace: pop
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: hub-k3d
      versionId: 3b897af6-d2f0-4b12-bce6-98e75af8d4ba
