---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-secret-operator
  namespace: aws-secret-operator
  labels:
    k8s-app: aws-secret-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-secret-operator
  template:
    metadata:
      labels:
        k8s-app: aws-secret-operator
        name: aws-secret-operator
    spec:
      serviceAccountName: aws-secret-operator
      containers:
        - name: aws-secret-operator
          image: mumoshu/aws-secret-operator:0.3.3
          command:
            - aws-secret-operator
          ports:
            - containerPort: 60000
              name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aws-secret-operator"
            - name: AWS_REGION
              value: "eu-central-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: api_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: api_secret_key
