apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  hub.server: |
    traefik-hub.app:53 {
        errors
        rewrite name regex (.*) traefikee-gslb-proxy-svc.pop.svc.cluster.local
        forward . 127.0.0.1
    }
    docker.localhost:53 {
        errors
        rewrite name sso.portal.docker.localhost hydra.hydra.svc.cluster.local
        rewrite name platform.docker.localhost traefik.traefik.svc.cluster.local
        rewrite name webapp.docker.localhost traefik.traefik.svc.cluster.local
        rewrite name regex (.*)\.tls\.docker\.localhost traefikee-gslb-proxy-svc.pop.svc.cluster.local
        forward . 127.0.0.1
    }
    k3d.hub-check.pop.svc.cluster.local:53 {
        errors
        rewrite name k3d.hub-check.pop.svc.cluster.local hub-check.pop.svc.cluster.local
        forward . 127.0.0.1
    }