---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-notification
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-notification
  template:
    metadata:
      labels:
        app: hub-notification
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: hub-notification
          image: gcr.io/traefiklabs/hub-notification:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: hub-secret
            - name: JWT_ISS
              value: "https://traefiklabs-hub-preview.eu.auth0.com/"
            - name: JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: hub-secret
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: sendgrid-api-key
                  name: hub-secret
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: LOG_LEVEL
              value: debug
            - name: LOG_FORMAT
              value: console
            - name: WORKSPACE_SERVICE_URL
              value: "http://hub-workspace.hub.svc.cluster.local/internal"
            - name: CLUSTER_SERVICE_URL
              value: "http://hub-cluster.hub.svc.cluster.local/internal"
            - name: USER_SERVICE_URL
              value: "http://hub-user.hub.svc.cluster.local/internal"
            - name: SENDGRID_ALERT_TEMPLATE_ID
              value: d-e31e1f5ce35c4b95b8390d19ce1a2543
            - name: SENDGRID_CUSTOMER_TRIAL_ENDING_TEMPLATE_ID
              value: d-d86128b08bc840119959e0acce0bb729
            - name: SENDGRID_CUSTOMER_LICENSE_ENDING_TEMPLATE_ID
              value: d-511a67561089435fa14046ccdbca85b2
            - name: SENDGRID_SALES_TRIAL_ENDING_TEMPLATE_ID
              value: d-d6657644ab2444eab8989ff62a6e5b77
            - name: SENDGRID_SALES_LICENSE_ENDING_TEMPLATE_ID
              value: d-dfd85f877e1c48998243f9bdfae5da5f
            - name: SENDGRID_INVITATION_TEMPLATE_ID
              value: d-31a4a51c91f245728e419d5980fe1bbc
            - name: SENDGRID_BETA_INVITATION_TEMPLATE_ID
              value: d-57cb9d7ad67e4fddb83db4c9b372eb91
            - name: SENDGRID_WELCOME_TEMPLATE_ID
              value: d-267cf2806d0f4cdc99a1c1d2cbd6d3dc
            - name: SENDGRID_UNVERIFIED_EMAIL_REMINDER_TEMPLATE_ID
              value: d-a06cdfd675e649459394b9e16a676b44
            - name: SENDGRID_NO_CLUSTER_REMINDER_TEMPLATE_ID
              value: d-5f561710d8d74ecab6dbcddb62c3f954
            - name: SENDGRID_REQUEST_SCALE_OFFER_TEMPLATE_ID
              value: d-5214ae9100c943dd8194aa3af6679ee8
            - name: SENDGRID_DEPRECATED_AGENT_15DAYS_TEMPLATE_ID
              value: d-0ffc1f69318d42c5a32aac103c8dd25b
            - name: SENDGRID_DEPRECATED_AGENT_5DAYS_TEMPLATE_ID
              value: d-835d0c6aa1d44255b99c79f2e8722b71
            - name: SENDGRID_DEPRECATED_AGENT_TEMPLATE_ID
              value: d-1869455d64e5485498a3dbda938bd6a7
            - name: SENDGRID_SALES_TRIAL_ENDED_TEMPLATE_ID
              value: d-62cf0f3717c74acca7df96fd88f2ca3d
            - name: SENDGRID_SALES_LICENSE_ENDED_TEMPLATE_ID
              value: d-b92039adc5af4ff89f2d1700405c4f2c
          args:
            - serve
            - --addr=:80
            - --sendgrid-host=https://api.sendgrid.com/v3/
            - --sendgrid-endpoint=/mail/send
            - --sendgrid-from=noreply@traefik.io
            - --sendgrid-from-name=Me
            - --sendgrid-sales-email=${GCLOUD_EMAIL}
            - --mongodb-uri=mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/notification?authSource=admin

---
apiVersion: v1
kind: Service
metadata:
  name: hub-notification
  namespace: hub
  labels:
    app: hub-notification
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: hub-notification
  selector:
    app: hub-notification
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: notification-external-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/notification/external`)
      services:
        - name: hub-notification
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: notification-external
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/notification/external`)
      services:
        - name: hub-notification
          port: 80
      middlewares:
        - name: stripprefix

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: notification-internal-tls
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/notification/internal`)
      services:
        - name: hub-notification
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: notification-internal
  namespace: hub
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/notification/internal`)
      services:
        - name: hub-notification
          port: 80
      middlewares:
        - name: stripprefix
