---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: neo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo
  template:
    metadata:
      labels:
        app: neo
    spec:
      containers:
      - name: neo
        image: gcr.io/traefiklabs/neo-agent:latest
        imagePullPolicy: IfNotPresent
