---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: neo-agent
  namespace: neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo-agent
  template:
    metadata:
      labels:
        app: neo-agent
    spec:
      serviceAccountName: neo-agent
      containers:
        - name: neo-agent
          image: gcr.io/traefiklabs/neo-agent:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
              - mountPath: /var/run/neo-agent/
                name: certs
          args:
            - --log-format="console"
      volumes:
        - name: certs
          secret:
            secretName: neo-certs
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem

---
apiVersion: v1
kind: Service
metadata:
  name: neo-agent
  namespace: neo
  labels:
    app: neo-agent
spec:
  type: ClusterIP
  ports:
    - port: 443
      name: neo-agent-webhook
    - port: 80
      name: neo-agent-auth
  selector:
    app: neo-agent

---
apiVersion: v1
kind: Secret
metadata:
  name: neo-certs
  namespace: neo
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSVENDQWkyZ0F3SUJBZ0lSQU14cGh5RmlVQVNBQTEyWjh5OXd4U013RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFXTnRaU0JEYnpBZ0Z3MHlNVEF4TWpBd09UTXdORGRhR0E4eU1USXdNVEl5TnpBNQpNekEwTjFvd0VqRVFNQTRHQTFVRUNoTUhRV050WlNCRGJ6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFQUzJ0b3FkcmpYeTEyVDNyeE1LRTFSaSt2dkgrYWdsNGo4ZkErUUpleXlpRVN4eEJQanYKWTlta2VVVWpHYWRzQWVFZ0wvNHRncWlJSHZVUys2VFJxTHNzcWVENEwzL3dnRm11cmZDc1k2Y3dRYmdxWG9jRApsczRrakNTTmlwN3g1enJtbjZsclZGTmJPRnRlbEtWR1FyZ1Q3T3N1dGtoZWk4clI0MnpkM2RHZ0hzSzlMQkFrClk4aVlHNm1STWhEenVtV0kvZjV2UmpoMjVlTk1YK29OUVEwQnJEeWM5b08yUHQwdEI0M1VnNEdiQW1DZW1PV0MKOFlaWkJEZVRZTG9GNEw1clpqZS83eSt4MzVxN1VrY2tiWG1BR21MZ0I1MlVGZ2ZIYzFRYnQyTFNQUFJadlFuMwppYVRXYTk0WU95Nlp4L3czZ3NKSFVFbWhjODhHQ1oxOEt2Y0NBd0VBQWFPQmt6Q0JrREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVxdzVEVk9NWlRsQWhuYnpFcVhDZXpTNktmUEF3T1FZRFZSMFJCREl3TUlJZGJtVnZMbVJsWm1GMQpiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDRDI1bGJ5NWtaV1poZFd4MExuTjJZekFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQUwxcE9BTDBmWWw2eUcyUktXa2kyVmxLVStkMi81SSs0eEhOYXM2ZThvVlI5MjJrQS8rM0YKVGx3VlVwbHpZcHVFUWhMYkFDcG44TTE0czZQUVkwWHNwbUFDbDFnUlJmTnkxU1JkZ21yTS9SL2VwMWFubDU2aApTcXJQd1FZaUtzK05xc1FPNVpwRnFHMVB4bWNCZUkySTNaNFNPRm8rMjhubUVpKzNnQWJ1Skg2TFlkSHpNWkRUClRZUUowMHlnU0FIS3YzRzQraDNqOUo3Q2IzOEo3ZG5Lb1FiM2RLdWxBK0lCbnp2ME80aUtqUEpmTTBpWm9GbzIKOTRwTGoremJCSHpnZm9vcUNoQ2JlY1U1ZzN0aTNGTk5YUjNtb08rMS9DMmNOZlJ4NVh6WGpXRGc5VGh2L0NDagpOa2REcm10U2R6WEFtMDhEUjNBbWtVL2l6WjMwakZ6NzRRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRDB0cmFLbmE0MTh0ZGsKOTY4VENoTlVZdnI3eC9tb0plSS9Id1BrQ1hzc29oRXNjUVQ0NzJQWnBIbEZJeG1uYkFIaElDLytMWUtvaUI3MQpFdnVrMGFpN0xLbmcrQzkvOElCWnJxM3dyR09uTUVHNEtsNkhBNWJPSkl3a2pZcWU4ZWM2NXArcGExUlRXemhiClhwU2xSa0s0RSt6ckxyWklYb3ZLMGVOczNkM1JvQjdDdlN3UUpHUEltQnVwa1RJUTg3cGxpUDMrYjBZNGR1WGoKVEYvcURVRU5BYXc4blBhRHRqN2RMUWVOMUlPQm13SmducGpsZ3ZHR1dRUTNrMkM2QmVDK2EyWTN2Kzh2c2QrYQp1MUpISkcxNWdCcGk0QWVkbEJZSHgzTlVHN2RpMGp6MFdiMEo5NG1rMW12ZUdEc3VtY2Y4TjRMQ1IxQkpvWFBQCkJnbWRmQ3IzQWdNQkFBRUNnZ0VBTWgwY3dzUkp3ZGlLVGEzL1YyblB6WTg3a01aQ0ZUSTA0L0pKRExENFhZcU8KODhmdFdjRkVkSFNmTlE1Y0daSWZ6R2VZREhocmNuSDF6UUJuTWppUlVrdHlPcFQ0dlQyV08wZHZiWU1RSVZQYgprWWh6dFRpQjhKTkJjOWJjbFhJNmhUQm5iLzEvMWxZdTgxOHFGN0tNeFQrblcvNUQ3QXdZbXA5aThJOTY5b3RxCldCRDc3N2NETU1IWE11b2s1S1hwUFBUVUgvbjZmckRQMnZXWkpnS0xVSWlrNkhMSG9IZ213ZGVRMkIxK1ZOSXkKQUxPTG54SHpITnNpVlJxZEV3bTBtaW94d0RiU0ZYeDVUN1V0QkN0RXB1NmpwakR0VHVGRVowM3ZHdmhFcDRpcgowdjBRYkdyV1kyNjVad01QaWE3NCtCSHZtdDJXYTRIUGFiUDM1cGVBaVFLQmdRRC9mR3EvU25LMm5KK1I3bWppCnQ1ZXlRRE5ORVdneTBUY3U3RjlNSlRTTnQ2UGJMY2VuUHZwck9kR1dBanFnQ2YxRDBha1hOSTRJMkxYdGJHRjMKNFNLeTAwNXZVczBFSDIxMitDQmQ3TXd3T21wOXIrdDRpN0p0L1ByanB2ZUNtaXVEWXNxQy9QenFONUpDb1JYZQpQMjFlaVpONytNZm9BYThNQkFxaitWZFdpd0tCZ1FEMU5MOStTZGYveE9RbDZ4K2RtTk1LVXFlWWlJQ3EwdHloCmdvLzl2c2xnbitSRDAvUzVXMGk1OGR5dUNYTGtQa2w1NlRXaEU0WHkxR1JVZnRjbU40Qm1JamszS3ZyWStaaVIKMVROc1JLdW40M3VTNFAySWtiQjFLTXdFOHQ3NC9SNkdpQS85emRGczVLSUMzWU5WdXB6L0tkVzQxVU5XQmwwMApvQVRPOFBmMnhRS0JnRkdVcWdXQlFWWWNkenZERkV6bzhSQ2pQWDVyZzRsT2t6OXhqUkNraEw2SUdGT0JyOUl3CjR3ZmdRNU9TREtSVDdFSityVzdTZ2xSQzF2MEVjYTgwL2I1NmlQNDFRM0FBbFJTN01LS3RYWm84M1FwYlpXWnQKdlVFdjJmRmR2SVZBczRwVnZuTExVL3Q2V1VMYmF6ODNvN1hmV20vb3hmVElyTnU2WXFkdmxEcjNBb0dBVXJXYQpLaVVLWU5HdkMwTkdCTWk1MXUrT2JKc09tNUJJcjRuMHUraVEwTERlTkNyWWozVkZFTU9PWm4zMWJSdTllUXU2CjlUdzZvSEFYNzVCaFRoakdqS3phazh0QmxkS0xMaFcySkx6OUVjSmZ1bWw5MjRVWStrdnFsWGkrMFVtLzlDME4KQjlWVzRONDE3N1Y4U1h5SzNGN21JbFI5UkJVZGQxVEtpbXNwbU9rQ2dZQml4RVdQODM0dmVSaDdtcGxONWxuNwptUy91VjBQU1E3aXVEY2thL0ZKaUNHUnVwY29BNmkwbHFLZExFQUtFRU9WKzVXVDBOc2d3RW1pYUE4QmEzVmZ6CmVCT1F4NENFMkZ1SnpJdktFL3h6dzkxTG1yMkhBZmNTNzFMeWlFUFFrUUlMNE5FK2d2QjZFSWJPUW5uWWNxZlEKVXZwUGx1ajdvK3YvaFdJb2c3N1BvUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
