apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: neo-adm-ctrlr
  namespace: neo
webhooks:
  - name: neo-agent.neo.svc.cluster.local
    clientConfig:
      service:
        name: neo-agent
        namespace: neo
        path: /
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdLZ0F3SUJBZ0lRSVZWKzVYQ0pPV295Z0tpNmxHandTVEFLQmdncWhrak9QUVFEQWpBU01SQXcKRGdZRFZRUUtFd2RCWTIxbElFTnZNQ0FYRFRJeE1ETXdNekE1TlRrME1sb1lEekl4TWpFd01qQTNNRGsxT1RReQpXakFTTVJBd0RnWURWUVFLRXdkQlkyMWxJRU52TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFCjFxeWc5cFpUcXJGUWd4Y3BoYmw5anJXYXdkbGJmeU9YSFZ2MlZQemNueDhhQmpFK3h4Z2srRWd1eDcwV2NXaVQKNWhVdDBGOTlIUGg0SnRMdk9KdXd1Nk9CbHpDQmxEQU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0V3WURWUjBsQkF3dwpDZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVS1FxT1hIbEhXTWZjCi92M3ppOFFZYnd4SGVKMHdQUVlEVlIwUkJEWXdOSUlmYm1WdkxXRm5aVzUwTG01bGJ5NXpkbU11WTJ4MWMzUmwKY2k1c2IyTmhiSUlSYm1WdkxXRm5aVzUwTG01bGJ5NXpkbU13Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnR2hmYwphNEdmZEM3L1hiYzgyRTF5YVVPY0tVYi91bnRPOVU0Uy8yc0lWREVDSUVpaTE2TC9UeHoyUlM1WmowQ0p1RGwxCnB2clZmVGUzZHRtRm1YVDE4ODExCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    sideEffects: None
    admissionReviewVersions: [ "v1" ]
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "extensions" ]
        apiVersions: [ "v1beta1" ]
        resources: [ "ingresses" ]
        scope: "Namespaced"
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "networking.k8s.io" ]
        apiVersions: [ "v1beta1" ]
        resources: [ "ingresses" ]
        scope: "Namespaced"
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "networking.k8s.io" ]
        apiVersions: [ "v1" ]
        resources: [ "ingresses" ]
        scope: "Namespaced"
