---
apiVersion: v1
kind: Secret
metadata:
  name: nats-auth
  namespace: nats
type: Opaque
stringData:
  NATS_SERVER_USER: traefik
  NATS_SERVER_PASSWORD: traefik
  NATS_HUB_USER: traefik-hub
  NATS_HUB_PASSWORD: traefik-hub
