---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-traefik-tls
  namespace: whoami
#  annotations:
#    hub.traefik.io/enable-acme: "true"
spec:
  ingressClassName: traefik-lb
  rules:
    - host: traefik.tls.docker.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80

  tls:
    - secretName: tls-secret
      hosts:
        - traefik.tls.docker.localhost

