# kubectl create secret generic minica -n traefik --from-file=minica.pem --output=yaml > minica.yaml
---
apiVersion: v1
data:
  minica.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQVlLZ0F3SUJBZ0lJTG9UWUVXY1JQK3d3Q2dZSUtvWkl6ajBFQXdNd0lERWVNQndHQTFVRUF4TVYKYldsdWFXTmhJSEp2YjNRZ1kyRWdNbVU0TkdRNE1DQVhEVEkwTVRBeE5EQTROVEEwT0ZvWUR6SXhNalF4TURFMApNRGcxTURRNFdqQWdNUjR3SEFZRFZRUURFeFZ0YVc1cFkyRWdjbTl2ZENCallTQXlaVGcwWkRnd2RqQVFCZ2NxCmhrak9QUUlCQmdVcmdRUUFJZ05pQUFScmlvbE1OKzJsVWZMWnZmaSt0c2pYbDJUeWREUTlsQjRld25mT2RBcEMKOWVDeXcxTFJEc3E4Y1IrRkRjZWUwdXA1Y1hpNUorWldGSE1GK05BWks4ZjB4WWFBaUl0U05oRGxCVzZ5UWxHagpCV1VrQmFGdGhhWlNGYkZJK0p5dC94aWpnWVl3Z1lNd0RnWURWUjBQQVFIL0JBUURBZ0tFTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWQKRGdRV0JCU2M0cHZyQnJCK1g2aTA0dnFneVM2V00rZUdkekFmQmdOVkhTTUVHREFXZ0JTYzRwdnJCckIrWDZpMAo0dnFneVM2V00rZUdkekFLQmdncWhrak9QUVFEQXdObkFEQmtBakFpN2U4eEpFOHN3N1JjZURDM1dMd1dtTjJPCk45K1IzN2wrcHpFOENoZlU4L0cxVGNtZjNmNGJrU1A5TjRmWW42Z0NNQ0pGc0x0TWpvRlBoU1d0aXFNRTdZZlQKdUV4U3krRmNhVTNqd2g3YTlLZjN2U0FZK2ZqZHBncGdPVUxERkVubi9BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
kind: Secret
metadata:
  name: minica
  namespace: traefik
type: Opaque
---
apiVersion: v1
data:
  minica.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQVlLZ0F3SUJBZ0lJTG9UWUVXY1JQK3d3Q2dZSUtvWkl6ajBFQXdNd0lERWVNQndHQTFVRUF4TVYKYldsdWFXTmhJSEp2YjNRZ1kyRWdNbVU0TkdRNE1DQVhEVEkwTVRBeE5EQTROVEEwT0ZvWUR6SXhNalF4TURFMApNRGcxTURRNFdqQWdNUjR3SEFZRFZRUURFeFZ0YVc1cFkyRWdjbTl2ZENCallTQXlaVGcwWkRnd2RqQVFCZ2NxCmhrak9QUUlCQmdVcmdRUUFJZ05pQUFScmlvbE1OKzJsVWZMWnZmaSt0c2pYbDJUeWREUTlsQjRld25mT2RBcEMKOWVDeXcxTFJEc3E4Y1IrRkRjZWUwdXA1Y1hpNUorWldGSE1GK05BWks4ZjB4WWFBaUl0U05oRGxCVzZ5UWxHagpCV1VrQmFGdGhhWlNGYkZJK0p5dC94aWpnWVl3Z1lNd0RnWURWUjBQQVFIL0JBUURBZ0tFTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWQKRGdRV0JCU2M0cHZyQnJCK1g2aTA0dnFneVM2V00rZUdkekFmQmdOVkhTTUVHREFXZ0JTYzRwdnJCckIrWDZpMAo0dnFneVM2V00rZUdkekFLQmdncWhrak9QUVFEQXdObkFEQmtBakFpN2U4eEpFOHN3N1JjZURDM1dMd1dtTjJPCk45K1IzN2wrcHpFOENoZlU4L0cxVGNtZjNmNGJrU1A5TjRmWW42Z0NNQ0pGc0x0TWpvRlBoU1d0aXFNRTdZZlQKdUV4U3krRmNhVTNqd2g3YTlLZjN2U0FZK2ZqZHBncGdPVUxERkVubi9BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
kind: Secret
metadata:
  name: minica
  namespace: pebble
type: Opaque
