---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-invitation
  namespace: neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo-invitation
  template:
    metadata:
      labels:
        app: neo-invitation
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: neo-invitation
          image: gcr.io/traefiklabs/neo-invitation:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
            - name: NEO_JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: neo-secret
            - name: NEO_JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: neo-secret
            - name: ORGANIZATION_SERVICE_URL
              value: http://neo-organization.neo.svc.cluster.local/internal
            - name: NOTIFICATION_SERVICE_URL
              value: http://neo-notification.neo.svc.cluster.local/internal
            - name: INVITATION_LINK_BASE_URL
              value: https://webapp.docker.io/r
            - name: LOG_LEVEL
              value: debug
          args:
            - serve
            - --addr=:80
            - --mongodb-uri=mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/invitations?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: neo-invitation
  namespace: neo
  labels:
    app: neo-invitation
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: neo-invitation
  selector:
    app: neo-invitation
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: invitation-external-tls
  namespace: neo
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/invitation/external`)
      services:
        - name: neo-invitation
          port: 80
      middlewares:
        - name: stripprefix
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: invitation-external
  namespace: neo
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`platform.docker.localhost`) && PathPrefix(`/invitation/external`)
      services:
        - name: neo-invitation
          port: 80
      middlewares:
        - name: stripprefix
