---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-organization
  namespace: neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo-organization
  template:
    metadata:
      labels:
        app: neo-organization
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: neo-organization
          image: gcr.io/traefiklabs/neo-organization-service:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
              httpGet:
                port: 80
                path: /ready
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 2
          env:
            - name: NEO_JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: neo-secret
            - name: NEO_JWT_ISS
              value: "https://traefiklabs-neo-dev.eu.auth0.com/"
            - name: NEO_JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: neo-secret
            - name: AUTH0_URL
              value: "https://traefiklabs-neo-dev.eu.auth0.com"
            - name: AUTH0_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth0-admin-token
                  key: token
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_USERNAME
              value: jaeger
            - name: TRACING_PASSWORD
              value: "jaeger"
            - name: TRACING_PROBABILITY
              value: "1"
          args:
            - serve
            - --addr=:80
            - --mongodb-uri=mongodb://admin:admin@mongodb.mongo.svc.cluster.local:27017/organizations?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: neo-organization
  namespace: neo
  labels:
    app: neo-organization
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: neo-organization
  selector:
    app: neo-organization
