---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-ui
  namespace: neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo-ui
  template:
    metadata:
      labels:
        app: neo-ui
        version: "v1"
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: neo-ui
          image: gcr.io/traefiklabs/neo-ui:latest
          imagePullPolicy: Always
          env:
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: auth0-client-id
                  name: neo-secret
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: auth0-client-secret
                  name: neo-secret
            - name: AUTH0_AUDIENCE
              value: https://clients.neo.traefik.io/
            - name: AUTH0_COOKIE_LIFETIME
              value: "7200"
            - name: AUTH0_COOKIE_SECRET
              value: supersecretcookiewith32charactersatleast
            - name: AUTH0_DOMAIN
              value: "https://traefiklabs-neo-dev.eu.auth0.com"
            - name: AUTH0_SCOPE
              value: openid profile email offline_access
            - name: DEPLOY_URL
              value: "https://webapp.docker.localhost"
            - name: AUTH0_ADMIN_TOKEN
              value: "toto"
            - name: TOPOLOGY_SERVICE_ENDPOINT
              value: "http://neo-topology.neo.svc.cluster.local/external"
            - name: METRICS_SERVICE_ENDPOINT
              value: "http://neo-metrics.neo.svc.cluster.local/external"
            - name: ORGANIZATION_SERVICE_ENDPOINT
              value: "http://neo-organization.neo.svc.cluster.local/external"
            - name: CLUSTER_SERVICE_ENDPOINT
              value: "http://neo-cluster.neo.svc.cluster.local/external"
            - name: IS_LOCAL
              value: "true"
            - name: "NODE_TLS_REJECT_UNAUTHORIZED"
              value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: neo-ui
  namespace: neo
  labels:
    app: neo-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: neo-ui
  selector:
    app: neo-ui

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: neo-ui
  namespace: neo
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`webapp.docker.localhost`)
      services:
        - name: neo-ui
          port: 80
  tls:
    certResolver: default
