---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-ingress-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-ingress-controller
  namespace: haproxy-ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-ingress-controller
  namespace: haproxy-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: haproxy-ingress-controller
  namespace: haproxy-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-ingress-controller
  namespace: haproxy-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy-ingress-controller
subjects:
  - kind: ServiceAccount
    name: haproxy-ingress-controller
    namespace: haproxy-ingress-controller
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: haproxy-ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: haproxy-ingress-controller
  namespace: haproxy-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: haproxy-ingress-controller
subjects:
  - kind: ServiceAccount
    name: haproxy-ingress-controller
    namespace: haproxy-ingress-controller
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: haproxy-ingress-controller
---
# Source: haproxy-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress-controller
data:
  ssl-redirect: "false"
  prometheus-port: "9105"
---
# see https://kubernetes.io/docs/reference/workloads-18-19
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: haproxy-ingress-controller
spec:
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9105"
    spec:
      serviceAccountName: haproxy-ingress-controller
      containers:
        - name: haproxy-ingress
          image: quay.io/jcmoraisjr/haproxy-ingress:v0.13.0-snapshot.1
          args:
            - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
            - --configmap=$(POD_NAMESPACE)/haproxy-ingress
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: stat
              containerPort: 1936
            - name: metrics
              containerPort: 9105
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10253
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
# Source: haproxy-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress-controller
spec:
  ports:
    - name: "http-80"
      port: 8000
      protocol: TCP
      targetPort: http
    - name: "https-443"
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    run: haproxy-ingress
  type: "LoadBalancer"
