---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-storage
  namespace: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
