---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:4.2.11
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_ROOT_PASSWORD
              value: admin
            - name: MONGODB_REPLICA_SET_MODE
              value: primary
            - name: MONGODB_REPLICA_SET_KEY
              value: replicatsetkey
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: "mongodb.mongo.svc.cluster.local"
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: "mongodb.mongo.svc.cluster.local"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongo
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
