
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: ghcr.io/zcube/bitnami-compat/mongodb:5.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_ROOT_PASSWORD
              value: admin
            - name: MONGODB_REPLICA_SET_MODE
              value: primary
            - name: MONGODB_REPLICA_SET_KEY
              value: replicatsetkey
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: mongodb-0.mongodb.mongo.svc.cluster.local
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: mongodb-0.mongodb.mongo.svc.cluster.local
          ports:
            - containerPort: 27017
          livenessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 2
          readinessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 2
          volumeMounts:
            - name: mongodb-storage
              mountPath: /bitnami/mongodb
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongo
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
