{
 "title": "HAProxy Ingress",
 "description": "HAProxy Ingress controller dashboard",
 "tags": [
  "haproxy",
  "ingress-controller",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "backend",
    "query": {
     "query": "label_values(haproxy_backend_sessions_total,proxy)"
    }
   },
   {
    "name": "public_frontend",
    "query": "(_tcp_.*|_front_http|_front[0-9]*)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HAProxy proc use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100*max(rate(haproxyingress_haproxy_processing_seconds_total[1m]))"
    }
   ]
  },
  {
   "title": "HAProxy running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(haproxy_ingress_update_success)-count(haproxy_process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Current sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*max(sum(haproxy_frontend_current_sessions) by (hostname)/max(haproxy_process_max_connections) by (hostname))"
    }
   ]
  },
  {
   "title": "Connections / s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$public_frontend\",hostname=~\"$hostname\"}[1m]))"
    }
   ]
  },
  {
   "title": "HAProxy threads p/proc",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "min(haproxy_process_nbthread)" }
   ]
  },
  {
   "title": "HAProxy uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-max(haproxy_process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Reload successful",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(haproxyingress_update_success)"
    }
   ]
  },
  {
   "title": "Certificate expiring",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(min(haproxyingress_cert_expire_date_epoch)-time())/3600/24"
    }
   ]
  },
  {
   "title": "HTTP request rate / s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"(_front[0-9]+|_front_http)\",hostname=~\"$hostname\"}[1m]))"
    }
   ]
  },
  {
   "title": "Controller instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(haproxyingress_update_success)"
    }
   ]
  },
  {
   "title": "Controller uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-max(process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "HAProxy process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HAProxy process use",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100*rate(haproxyingress_haproxy_processing_seconds_total[1m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Admin socket response time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxyingress_haproxy_response_time_seconds_sum{command=\"show_info\"}[1m])/rate(haproxyingress_haproxy_response_time_seconds_count{command=\"show_info\"}[1m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Full reloads (1m)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(haproxyingress_updates_total{status=\"full\"}[1m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Admin socket response time above 10ms",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100-(100*increase(haproxyingress_haproxy_response_time_seconds_bucket{command=\"show_info\",le=\"0.01\"}[1m]) / ignoring (le) increase(haproxyingress_haproxy_response_time_seconds_count{command=\"show_info\"}[1m]))",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100*rate(process_cpu_seconds_total[1m])",
       "legendFormat": "{{hostname}} | {{job}}"
      }
     ]
    },
    {
     "title": "Controller sync rate (1m)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(haproxyingress_updates_total[1m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection rate (conn/s)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$public_frontend\",hostname=~\"$hostname\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "HTTP request/response rate (req/s)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"(_front[0-9]+|_front_http)\",hostname=~\"$hostname\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Current sessions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(haproxy_frontend_current_sessions) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Current sessions / max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100*sum(haproxy_frontend_current_sessions) by (hostname)/min(haproxy_process_max_connections) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Cluster wide bytes in/out rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$public_frontend\",hostname=~\"$hostname\"}[1m]))",
       "legendFormat": "in"
      },
      {
       "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$public_frontend\",hostname=~\"$hostname\"}[1m]))",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Bytes in/out rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$public_frontend\",hostname=~\"$hostname\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} in"
      },
      {
       "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$public_frontend\",hostname=~\"$hostname\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} out"
      }
     ]
    }
   ]
  },
  { "title": "Backend responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Top 5 4xx responses / minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(increase(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=\"4xx\"}[1m])) by (proxy,code))",
     "legendFormat": "{{code}} - {{proxy}}"
    }
   ]
  },
  {
   "title": "Top 5 5xx responses / minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(increase(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"5xx|other\"}[1m])) by (proxy,code))",
     "legendFormat": "{{code}} - {{proxy}}"
    }
   ]
  },
  {
   "title": "Backend status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 request/response rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 bytes in/out rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}} in"
      },
      {
       "expr": "topk(5,sum(rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}} out"
      }
     ]
    },
    {
     "title": "Top 5 max/avg connection time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5,max(haproxy_backend_connect_time_average_seconds{proxy=~\"$backend\"}) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 current sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(haproxy_backend_current_sessions{proxy=~\"$backend\"}) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificate signing failures",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{success=\"false\"}[1m])) by (hostname,domains)",
       "legendFormat": "{{hostname}} | {{domains}}"
      }
     ]
    },
    {
     "title": "New certificates issued",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{reason=\"missing\",success=\"true\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} | missing"
      },
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{reason=\"expiring\",success=\"true\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} | expiring"
      },
      {
       "expr": "sum(increase(haproxyingress_cert_signing_count{reason=\"outdated\",success=\"true\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} | outdated"
      }
     ]
    },
    {
     "title": "Certificate expiration",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "min(1000*haproxyingress_cert_expire_date_epoch) by (cn)"
      }
     ]
    }
   ]
  }
 ]
}