{
 "title": "NATS Server Dashboard",
 "description": "NATS Server Dashboard for use with the Prometheus NATS Exporter",
 "tags": [ "nats" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(nats_varz_in_bytes,cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nats_varz_in_bytes{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nats_varz_cpu{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nats_varz_mem{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nats_varz_in_bytes{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nats_varz_in_msgs{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nats_varz_out_bytes{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nats_varz_out_msgs{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nats_varz_connections{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nats_varz_subscriptions{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nats_varz_slow_consumers{cluster=\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  }
 ]
}