---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hub-bandwidth-quota-enforcer
  namespace: pop
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            app: hub-bandwidth-quota-enforcer-job
        spec:
          serviceAccountName: secret-writer
          imagePullSecrets:
            - name: gcr-access-token
          restartPolicy: Never
          containers:
            - name: hub-bandwidth-quota-enforcer
              imagePullPolicy: IfNotPresent
              image: gcr.io/traefiklabs/hub-gslb:latest
              env:
                - name: MONGODB_URI
                  value: mongodb://root:admin@mongodb.mongo.svc.cluster.local:27017/workspaces?authSource=admin
                - name: GA_NAME
                  value: gslb-ga.docker.localhost
                - name: DEV_MODE
                  value: "true"
                - name: LOG_LEVEL
                  value: debug
              args:
                - enforce-bandwidth-quotas
