---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-cluster
  namespace: neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo-cluster
  template:
    metadata:
      labels:
        app: neo-cluster
    spec:
      imagePullSecrets:
        - name: gcr-access-token
      containers:
        - name: neo-cluster
          image: gcr.io/traefiklabs/neo-cluster:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 80
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: NEO_JWT_CERT
              valueFrom:
                secretKeyRef:
                  key: jwt-cert
                  name: neo-secret
            - name: NEO_JWT_ISS
              value: "https://traefiklabs-neo-dev.eu.auth0.com/"
            - name: NEO_JWT_SUB
              valueFrom:
                secretKeyRef:
                  key: jwt-sub
                  name: neo-secret
            - name: TOKEN_SERVICE_URL
              value: http://neo-token.neo.svc.cluster.local/internal
            - name: TOPOLOGY_SERVICE_URL
              value: http://neo-topology.neo.svc.cluster.local/internal
            - name: TOPOLOGY_GIT_PROXY_HOST
              value: platform.docker.localhost
            - name: TOPOLOGY_GIT_ORG_NAME
              value: "${GITHUB_ORG}"
            - name: TRACING_ENDPOINT
              value: "http://jaeger.jaeger.svc.cluster.local:14268"
            - name: TRACING_PROBABILITY
              value: "1"
          args:
            - serve
            - --addr=:80
            - --mongodb-uri=mongodb://admin:admin@mongodb.mongo.svc.cluster.local:27017/clusters?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: neo-cluster
  namespace: neo
  labels:
    app: neo-cluster
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: neo-cluster
  selector:
    app: neo-cluster
