---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: walkthrough-weather-api-forecast
  namespace: apps
spec: {}

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: walkthrough-weather-api-forecast
  namespace: apps
spec:
  apis:
  - name: walkthrough-weather-api-forecast
  everyone: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: walkthrough-weather-api-forecast
  namespace: apps
  annotations:
    hub.traefik.io/api: walkthrough-weather-api-forecast
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.walkthrough.docker.localhost`) && PathPrefix(`/forecast`)
    kind: Rule
    services:
    - name: weather-app-forecast
      port: 3000
    middlewares:
      - name: stripprefix-weather
