---
apiVersion: v1
kind: Secret
metadata:
  name: walkthrough-apikey-auth
  namespace: apps
stringData:
  secretKey: "{SHA}dhiZGvSW60OMQ+J6hPEyJ+jfUoU="

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: walkthrough-apikey-auth
  namespace: apps
spec:
  plugin:
    apiKey:
      keySource:
        header: Authorization
        headerAuthScheme: Bearer
      secretValues:
        - urn:k8s:secret:walkthrough-apikey-auth:secretKey

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: walkthrough-weather-api-api-key
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`walkthrough.docker.localhost`) && PathPrefix(`/api-key`)
    kind: Rule
    services:
    - name: weather-app
      port: 3000
    middlewares:
      - name: stripprefix-weather
      - name: walkthrough-apikey-auth
