---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: getting-started-apimanagement-weather-api-forecast
  namespace: apps
spec: {}

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: getting-started-apimanagement-weather-api-forecast
  namespace: apps
spec:
  apis:
  - name: getting-started-apimanagement-weather-api-forecast
  everyone: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: getting-started-apimanagement-weather-api-forecast
  namespace: apps
  annotations:
    hub.traefik.io/api: getting-started-apimanagement-weather-api-forecast
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`api.getting-started.apimanagement.docker.localhost`) && Path(`/forecast`)
    kind: Rule
    services:
    - name: weather-app-forecast
      port: 3000
