---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: hub-secret
  namespace: hub
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: hub-k3d
      versionId: defddc15-b10e-4e43-95f2-aecf22456702
