---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: hub-secret
  namespace: hub
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: hub-k3d
      versionId: 17f26f12-890e-480e-9ac3-c8ea96ba8f61
