---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  expose.apigateway.server: |
    expose.apigateway.docker.localhost {
        log
        rewrite name expose.apigateway.docker.localhost traefik.traefik.svc.cluster.local
        forward . 127.0.0.1
    }
