name: Embed code in markdown files

on:
  pull_request:
    branches:
      - main

jobs:
  embed-code:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.TRAEFIKER_GITHUB_TOKEN }}
      - name: embed code
        run: |
          python3 hack/mdce/mdce.py -s -g -u
      - name: commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: updates markdown content"
          committer_name: "traefiker@github"
          committer_email: "30906710+traefiker@users.noreply.github.com"
