---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-client-creds
  namespace: apps
spec:
  plugin:
    oAuthClientCredentials:
      url: http://hydra.hydra.svc:4444/oauth2/token
      audience: https://traefik.io
      usernameClaim: sub
      forwardHeaders:
        Sub: sub

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: secure-applications-apigateway-oauth2-client-credentials
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`secure-applications.apigateway.docker.localhost`) && Path(`/oauth2-client-credentials`)
    kind: Rule
    services:
    - name: whoami
      port: 80
    middlewares:
    - name: oauth2-client-creds
