---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-login
  namespace: apps
spec:
  plugin:
    oidc:
      issuer: http://hydra.hydra.svc:4444
      clientId: "urn:k8s:secret:oidc-client:client_id"
      clientSecret: "urn:k8s:secret:oidc-client:client_secret"
      loginUrl: /oidc/login
      logoutUrl: /oidc/logout
      redirectUrl: /oidc/callback
      csrf: {}
      session:
        name: "oidc-session"

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: secure-applications-apigateway-whoami-oidc
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`secure-applications.apigateway.docker.localhost`) && (Path(`/oidc`) || Path(`/oidc/login`) || Path(`/oidc/logout`) || Path(`/oidc/callback`))
    kind: Rule
    services:
    - name: whoami
      port: 80
    middlewares:
    - name: oidc-login
