---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-nologin
  namespace: apps
spec:
  plugin:
    oidc:
      issuer: http://hydra.hydra.svc:4444
      clientId: "urn:k8s:secret:oidc-client-nologin:client_id"
      clientSecret: "urn:k8s:secret:oidc-client-nologin:client_secret"
      logoutUrl: /oidc-nologin/logout
      redirectUrl: /oidc-nologin/callback
      csrf: {}
      session:
        name: "oidc-session"

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: secure-applications-apigateway-whoami-nologin
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`secure-applications.apigateway.docker.localhost`) && (Path(`/oidc-nologin`) || Path(`/oidc-nologin/logout`) || Path(`/oidc-nologin/callback`))
    kind: Rule
    services:
    - name: whoami
      port: 80
    middlewares:
    - name: oidc-nologin
